// RUN: echo '{"schema_version":1,"kind":"dfg_sim_report","workload":"toy","status":"pass","operation_semantics_source":"loom.sim.operation_semantics.v1","operation_cost_model_source":"loom.sim.operation_cost.v1","optimistic_cycles":3,"final_outputs":[],"final_memory_state":{}}' > %t.dfg.json
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":7,"config_records":0,"placements":[],"routes":[],"config_bitstream":[]}' > %t.bad-routes.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-routes.json --output %t.bad-routes.cgra.json 2>&1 | FileCheck %s --check-prefix=ROUTES
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":1,"config_records":2,"placements":[],"routes":[{"from":"arith.addi#0","to":"arith.muli#0","status":"routed"}],"config_bitstream":[{"target":"toy__toy_adg::route#0","register":"from_software_id","value":"arith.addi#0","source":"route:arith.addi#0->arith.muli#0"},{"target":"toy__toy_adg::route#0","register":"to_software_id","value":"arith.muli#0","source":"route:arith.addi#0->arith.muli#0"}]}' > %t.bad-route-segments.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-route-segments.json --output %t.bad-route-segments.cgra.json 2>&1 | FileCheck %s --check-prefix=SEGMENTS
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":1,"config_records":6,"placements":[],"routes":[{"record_id":"route#0","edge_ref":"arith.addi#0.result0->arith.muli#0.operand0","producer_binding":"placement:arith.addi#0","consumer_binding":"placement:arith.muli#0","payload_kind":"data","from":"arith.addi#0","to":"arith.muli#0","status":"routed","segments":[{"segment_id":"seg0","segment_kind":"module_path","source_endpoint":"toy_adg::fabric.op#0.out","sink_endpoint":"toy_adg::fabric.op#1.in"}]}],"config_bitstream":[{"target":"toy__toy_adg::route#0","register":"from_software_id","value":"arith.addi#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"to_software_id","value":"arith.muli#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment_count","value":"1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.kind","value":"module_path","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.source_endpoint","value":"toy_adg::fabric.op#0.out","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.sink_endpoint","value":"toy_adg::fabric.op#1.in","source":"route:route#0"}]}' > %t.optional-hardware-ref.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.optional-hardware-ref.json --output %t.optional-hardware-ref.cgra.json 2>&1 | FileCheck %s --check-prefix=NEEDS-HARDWARE
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":1,"config_records":14,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"spatial"},{"software":"arith.addi#1","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#1","schedule":"spatial"}],"routes":[{"record_id":"route#0","edge_ref":"arith.addi#0.result0->arith.addi#1.operand0","producer_binding":"placement:arith.addi#0","consumer_binding":"placement:arith.addi#1","payload_kind":"data","from":"arith.addi#0","to":"arith.addi#1","status":"routed","segments":[{"segment_id":"seg0","segment_kind":"module_path","source_endpoint":"toy_adg::fabric.op#0.out","sink_endpoint":"toy_adg::fabric.op#1.in"}]}],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"spatial","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#1","register":"software_id","value":"arith.addi#1","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"operation","value":"arith.addi","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"schedule","value":"spatial","source":"placement:arith.addi#1"},{"target":"toy__toy_adg::route#0","register":"from_software_id","value":"arith.addi#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"to_software_id","value":"arith.addi#1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment_count","value":"1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.kind","value":"module_path","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.source_endpoint","value":"toy_adg::fabric.op#0.out","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.sink_endpoint","value":"toy_adg::fabric.op#1.in","source":"route:route#0"}]}' > %t.placeholder-endpoints.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.placeholder-endpoints.json --hardware-mlir %s --output %t.placeholder-endpoints.cgra.json 2>&1 | FileCheck %s --check-prefix=PLACEHOLDER-ENDPOINT
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":1,"config_records":14,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"spatial"},{"software":"arith.addi#1","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#1","schedule":"spatial"}],"routes":[{"record_id":"route#0","edge_ref":"arith.addi#0.result0->arith.addi#1.operand0","producer_binding":"placement:arith.addi#0","consumer_binding":"placement:arith.addi#1","payload_kind":"data","from":"arith.addi#0","to":"arith.addi#1","status":"routed","segments":[{"segment_id":"seg0","segment_kind":"resource_edge","source_endpoint":"toy_adg::fabric.op#0.result0","sink_endpoint":"toy_adg::fabric.op#1.operand0"}]}],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"spatial","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#1","register":"software_id","value":"arith.addi#1","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"operation","value":"arith.addi","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#1"},{"target":"toy_adg::fabric.op#1","register":"schedule","value":"spatial","source":"placement:arith.addi#1"},{"target":"toy__toy_adg::route#0","register":"from_software_id","value":"arith.addi#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"to_software_id","value":"arith.addi#1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment_count","value":"1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.kind","value":"resource_edge","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.source_endpoint","value":"toy_adg::fabric.op#0.result0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.sink_endpoint","value":"toy_adg::fabric.op#1.operand0","source":"route:route#0"}]}' > %t.disconnected-endpoints.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.disconnected-endpoints.json --hardware-mlir %s --output %t.disconnected-endpoints.cgra.json 2>&1 | FileCheck %s --check-prefix=DISCONNECTED-ENDPOINT
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":1,"placements":[],"routes":[],"config_bitstream":[]}' > %t.bad-config-count.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-config-count.json --output %t.bad-config-count.cgra.json 2>&1 | FileCheck %s --check-prefix=CONFIG
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"dynamic"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"dynamic","source":"placement:arith.addi#0"}]}' > %t.bad-schedule.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-schedule.json --output %t.bad-schedule.cgra.json 2>&1 | FileCheck %s --check-prefix=SCHEDULE
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.cache","hardware":"toy_adg::fabric.cache#0","schedule":"spatial"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.cache#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"resource_kind","value":"fabric.cache","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"schedule","value":"spatial","source":"placement:arith.addi#0"}]}' > %t.bad-resource.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-resource.json --output %t.bad-resource.cgra.json 2>&1 | FileCheck %s --check-prefix=RESOURCE
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.fake#0","operation":"arith.fake","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"spatial"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.fake#0","source":"placement:arith.fake#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.fake","source":"placement:arith.fake#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.fake#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"spatial","source":"placement:arith.fake#0"}]}' > %t.bad-operation.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-operation.json --output %t.bad-operation.cgra.json 2>&1 | FileCheck %s --check-prefix=OPERATION

// ROUTES: mapping routed_edges field 7 does not match routes array size 0
// SEGMENTS: mapping route lacks non-empty segments
// NEEDS-HARDWARE: hardware MLIR is required to verify routed mapping
// PLACEHOLDER-ENDPOINT: mapping route segment endpoint uses placeholder suffix
// DISCONNECTED-ENDPOINT: mapping route segment is not present in hardware topology
// CONFIG: mapping config_records field 1 does not match config_bitstream size 0
// SCHEDULE: mapping placement schedule dynamic is not supported
// RESOURCE: mapping placement resource_kind fabric.cache is not supported
// OPERATION: mapping placement operation arith.fake is not supported by operation semantics

module {
  fabric.module @toy_adg(%a : !fabric.bits<32>, %b : !fabric.bits<32>) {
    fabric.pe [spatial] (%lhs = %a : !fabric.bits<32>,
                         %rhs = %b : !fabric.bits<32>)
        -> !fabric.bits<32> {
      fabric.fu(%fa = %lhs : !fabric.bits<32>,
                %fb = %rhs : !fabric.bits<32>) -> () {
        %sum = fabric.op [@arith.addi] (%fa, %fb)
               : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
        fabric.yield
      }
    }
    fabric.pe [spatial] (%lhs = %a : !fabric.bits<32>,
                         %rhs = %b : !fabric.bits<32>)
        -> !fabric.bits<32> {
      fabric.fu(%fa = %lhs : !fabric.bits<32>,
                %fb = %rhs : !fabric.bits<32>) -> () {
        %sum = fabric.op [@arith.addi] (%fa, %fb)
               : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
        fabric.yield
      }
    }
    fabric.yield
  }
}
