// RUN: echo '{"schema_version":1,"kind":"dfg_sim_report","workload":"toy","status":"pass","operation_semantics_source":"loom.sim.operation_semantics.v1","optimistic_cycles":3}' > %t.dfg.json
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":7,"config_records":0,"placements":[],"routes":[],"config_bitstream":[]}' > %t.bad-routes.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-routes.json --output %t.bad-routes.cgra.json 2>&1 | FileCheck %s --check-prefix=ROUTES
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":1,"placements":[],"routes":[],"config_bitstream":[]}' > %t.bad-config-count.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-config-count.json --output %t.bad-config-count.cgra.json 2>&1 | FileCheck %s --check-prefix=CONFIG
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"dynamic"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"dynamic","source":"placement:arith.addi#0"}]}' > %t.bad-schedule.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-schedule.json --output %t.bad-schedule.cgra.json 2>&1 | FileCheck %s --check-prefix=SCHEDULE
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.cache","hardware":"toy_adg::fabric.cache#0","schedule":"spatial"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.cache#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"resource_kind","value":"fabric.cache","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.cache#0","register":"schedule","value":"spatial","source":"placement:arith.addi#0"}]}' > %t.bad-resource.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.bad-resource.json --output %t.bad-resource.cgra.json 2>&1 | FileCheck %s --check-prefix=RESOURCE

// ROUTES: mapping routed_edges field 7 does not match routes array size 0
// CONFIG: mapping config_records field 1 does not match config_bitstream size 0
// SCHEDULE: mapping placement schedule dynamic is not supported
// RESOURCE: mapping placement resource_kind fabric.cache is not supported
