// RUN: echo '{"schema_version":1,"kind":"dfg_sim_report","workload":"toy","status":"pass","operation_semantics_source":"loom.sim.operation_semantics.v1","operation_cost_model_source":"loom.sim.operation_cost.v1","optimistic_cycles":3}' > %t.dfg.json
// RUN: echo 'fabric.module @toy_adg(%%a : !fabric.bits<32>, %%b : !fabric.bits<32>) { fabric.pe [spatial] (%%pa = %%a : !fabric.bits<32>, %%pb = %%b : !fabric.bits<32>) -> !fabric.bits<32> { fabric.fu(%%lhs = %%pa : !fabric.bits<32>, %%rhs = %%pb : !fabric.bits<32>) -> () { %%sum = fabric.op [@arith.addi] (%%lhs, %%rhs) : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32> fabric.yield } } fabric.yield }' > %t.hardware.mlir
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#1","schedule":"spatial"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.op#1","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#1","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#1","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#1","register":"schedule","value":"spatial","source":"placement:arith.addi#0"}]}' > %t.missing-resource.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.missing-resource.json --hardware-mlir %t.hardware.mlir --output %t.missing-resource.cgra.json 2>&1 | FileCheck %s --check-prefix=MISSING
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":0,"config_records":4,"placements":[{"software":"arith.muli#0","operation":"arith.muli","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"spatial"}],"routes":[],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.muli#0","source":"placement:arith.muli#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.muli","source":"placement:arith.muli#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.muli#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"spatial","source":"placement:arith.muli#0"}]}' > %t.unsupported-op.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.unsupported-op.json --hardware-mlir %t.hardware.mlir --output %t.unsupported-op.cgra.json 2>&1 | FileCheck %s --check-prefix=OPLIST
// RUN: echo '{"schema_version":1,"kind":"pnr_mapping","workload":"toy","hardware":"toy_adg","mapping_id":"toy__toy_adg","status":"pass","routed_edges":1,"config_records":10,"placements":[{"software":"arith.addi#0","operation":"arith.addi","resource_kind":"fabric.op","hardware":"toy_adg::fabric.op#0","schedule":"spatial"}],"routes":[{"record_id":"route#0","edge_ref":"arith.addi#0.result1->arith.addi#0.operand0","producer_binding":"placement:arith.addi#0","consumer_binding":"placement:arith.addi#0","payload_kind":"data","from":"arith.addi#0","to":"arith.addi#0","status":"routed","segments":[{"segment_id":"seg0","segment_kind":"module_path","source_endpoint":"toy_adg::fabric.op#0.result1","sink_endpoint":"toy_adg::fabric.op#0.operand0"}]}],"config_bitstream":[{"target":"toy_adg::fabric.op#0","register":"software_id","value":"arith.addi#0","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"operation","value":"arith.addi","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"resource_kind","value":"fabric.op","source":"placement:arith.addi#0"},{"target":"toy_adg::fabric.op#0","register":"schedule","value":"spatial","source":"placement:arith.addi#0"},{"target":"toy__toy_adg::route#0","register":"from_software_id","value":"arith.addi#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"to_software_id","value":"arith.addi#0","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment_count","value":"1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.kind","value":"module_path","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.source_endpoint","value":"toy_adg::fabric.op#0.result1","source":"route:route#0"},{"target":"toy__toy_adg::route#0","register":"segment.0.sink_endpoint","value":"toy_adg::fabric.op#0.operand0","source":"route:route#0"}]}' > %t.missing-route-endpoint.json
// RUN: not loom-cgra-sim --dfg-report %t.dfg.json --mapping-artifact %t.missing-route-endpoint.json --hardware-mlir %t.hardware.mlir --output %t.missing-route-endpoint.cgra.json 2>&1 | FileCheck %s --check-prefix=ROUTE-ENDPOINT

// MISSING: hardware artifact does not contain resource toy_adg::fabric.op#1
// OPLIST: hardware resource toy_adg::fabric.op#0 does not support operation arith.muli
// ROUTE-ENDPOINT: hardware artifact does not contain route endpoint toy_adg::fabric.op#0.result1
