Import('*')

import os


repo_root = os.path.abspath(os.path.join(Dir('.').srcnode().abspath, '..', '..'))
env.Append(CPPPATH=[repo_root, os.path.join(repo_root, 'include')])

SimObject('LoomSpatialBridge.py', sim_objects=['LoomSpatialBridge'])
Source('loom_spatial_bridge.cc')
