#ifndef LOOM_DIALECT_FABRIC_FABRICOPS_TD
#define LOOM_DIALECT_FABRIC_FABRICOPS_TD

include "loom/Dialect/Fabric/FabricDialect.td"
include "loom/Dialect/Fabric/FabricTypes.td"
include "loom/Dialect/Fabric/FabricTopOps.td"
include "loom/Dialect/Fabric/FabricPEOps.td"
include "loom/Dialect/Fabric/FabricSwitchOps.td"
include "loom/Dialect/Fabric/FabricMemOps.td"
include "loom/Dialect/Fabric/FabricMiscOps.td"
include "loom/Dialect/Fabric/FabricSystemOps.td"

#endif
