#ifndef FCC_DIALECT_FABRIC_FABRICOPS_TD
#define FCC_DIALECT_FABRIC_FABRICOPS_TD

include "fcc/Dialect/Fabric/FabricDialect.td"
include "fcc/Dialect/Fabric/FabricTypes.td"
include "fcc/Dialect/Fabric/FabricTopOps.td"
include "fcc/Dialect/Fabric/FabricPEOps.td"
include "fcc/Dialect/Fabric/FabricSwitchOps.td"
include "fcc/Dialect/Fabric/FabricMemOps.td"
include "fcc/Dialect/Fabric/FabricMiscOps.td"

#endif
