if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is not set")
endif()

file(GLOB TDD_OUTPUT_DIRS "${SOURCE_DIR}/tests/fabric/tdd/*/Output")
foreach(dir IN LISTS TDD_OUTPUT_DIRS)
  if(IS_DIRECTORY "${dir}")
    file(REMOVE_RECURSE "${dir}")
  endif()
endforeach()
