add_subdirectory(Common)
add_subdirectory(Evaluation)
add_subdirectory(DSE/Policy)
add_subdirectory(Config)
add_subdirectory(ExternalTool)
add_subdirectory(EDA)
add_subdirectory(ADG)
add_subdirectory(Fabric)
add_subdirectory(Dataflow)
add_subdirectory(Mapping)
add_subdirectory(Frontend)
add_subdirectory(Runtime)
add_subdirectory(Deployment)
add_subdirectory(Modeling)
add_subdirectory(DSE)
add_subdirectory(Simulator)
add_subdirectory(PnR)
add_subdirectory(ImplementationPlatform)
add_subdirectory(Hardware)
