"builtin.module"() ({
  "fabric.module"() ({
    "fabric.yield"() : () -> ()
  }) {function_type = () -> (), sym_name = "SC-FP"} : () -> ()
  "fabric.module"() ({
    "fabric.yield"() : () -> ()
  }) {function_type = () -> (), sym_name = "SC-SPM"} : () -> ()
  "fabric.module"() ({
    "fabric.yield"() : () -> ()
  }) {function_type = () -> (), sym_name = "SC-CTRL"} : () -> ()
  "fabric.module"() ({
    "fabric.instance"() {core_id = 0 : i64, grid_col = 0 : i64, grid_row = 0 : i64, khg_type = "SC-FP", mesh_col = 0 : i64, mesh_row = 0 : i64, module = @"SC-FP", sym_name = "SC-FP.0"} : () -> ()
    "fabric.instance"() {core_id = 1 : i64, grid_col = 1 : i64, grid_row = 0 : i64, khg_type = "SC-FP", mesh_col = 1 : i64, mesh_row = 0 : i64, module = @"SC-FP", sym_name = "SC-FP.1"} : () -> ()
    "fabric.instance"() {core_id = 2 : i64, grid_col = 2 : i64, grid_row = 0 : i64, khg_type = "SC-SPM", mesh_col = 2 : i64, mesh_row = 0 : i64, module = @"SC-SPM", sym_name = "SC-SPM.0"} : () -> ()
    "fabric.instance"() {core_id = 3 : i64, grid_col = 3 : i64, grid_row = 0 : i64, khg_type = "SC-SPM", mesh_col = 3 : i64, mesh_row = 0 : i64, module = @"SC-SPM", sym_name = "SC-SPM.1"} : () -> ()
    "fabric.instance"() {core_id = 4 : i64, grid_col = 0 : i64, grid_row = 1 : i64, khg_type = "SC-FP", mesh_col = 0 : i64, mesh_row = 1 : i64, module = @"SC-FP", sym_name = "SC-FP.2"} : () -> ()
    "fabric.instance"() {core_id = 5 : i64, grid_col = 1 : i64, grid_row = 1 : i64, khg_type = "SC-FP", mesh_col = 1 : i64, mesh_row = 1 : i64, module = @"SC-FP", sym_name = "SC-FP.3"} : () -> ()
    "fabric.instance"() {core_id = 6 : i64, grid_col = 2 : i64, grid_row = 1 : i64, khg_type = "SC-SPM", mesh_col = 2 : i64, mesh_row = 1 : i64, module = @"SC-SPM", sym_name = "SC-SPM.2"} : () -> ()
    "fabric.instance"() {core_id = 7 : i64, grid_col = 3 : i64, grid_row = 1 : i64, khg_type = "SC-CTRL", mesh_col = 3 : i64, mesh_row = 1 : i64, module = @"SC-CTRL", sym_name = "SC-CTRL"} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 6 : i64, pipeline_stages = 1 : i64, router_kind = "SC-FP", routing_strategy = "xy_dor", sym_name = "router_0", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 6 : i64, pipeline_stages = 1 : i64, router_kind = "SC-FP", routing_strategy = "xy_dor", sym_name = "router_1", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 5 : i64, pipeline_stages = 1 : i64, router_kind = "SC-SPM", routing_strategy = "xy_dor", sym_name = "router_2", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 5 : i64, pipeline_stages = 1 : i64, router_kind = "SC-SPM", routing_strategy = "xy_dor", sym_name = "router_3", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 6 : i64, pipeline_stages = 1 : i64, router_kind = "SC-FP", routing_strategy = "xy_dor", sym_name = "router_4", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 6 : i64, pipeline_stages = 1 : i64, router_kind = "SC-FP", routing_strategy = "xy_dor", sym_name = "router_5", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 5 : i64, pipeline_stages = 1 : i64, router_kind = "SC-SPM", routing_strategy = "xy_dor", sym_name = "router_6", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.router"() {buffer_depth = 4 : i64, flit_width_bits = 128 : i64, num_ports = 5 : i64, pipeline_stages = 1 : i64, router_kind = "SC-CTRL", routing_strategy = "xy_dor", sym_name = "router_7", topology_role = "mesh", virtual_channels = 2 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_0", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_1", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_2", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_3", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_4", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_5", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_6", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "l2_cache", num_banks = 1 : i64, port_count = 1 : i64, size_bytes = 65536 : i64, sym_name = "l2_bank_7", width_bytes = 32 : i64} : () -> ()
    "fabric.shared_mem"() {mem_type = "external_dram", num_banks = 8 : i64, port_count = 8 : i64, size_bytes = 524288 : i64, sym_name = "ext_mem_if", width_bytes = 32 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_4, dest_port = 0 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_0, source_port = 1 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_1, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_0, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_5, dest_port = 0 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_1, source_port = 1 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_2, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_1, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_0, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_1, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_6, dest_port = 0 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_2, source_port = 1 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_3, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_2, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_1, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_2, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_7, dest_port = 0 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_3, source_port = 1 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_2, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_3, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_0, dest_port = 1 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_4, source_port = 0 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_5, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_4, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_1, dest_port = 1 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_5, source_port = 0 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_6, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_5, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_4, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_5, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_2, dest_port = 1 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_6, source_port = 0 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_7, dest_port = 3 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_6, source_port = 2 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_5, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_6, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_3, dest_port = 1 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_7, source_port = 0 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 16 : i64, dest = @router_6, dest_port = 2 : i64, latency_cycles = 1 : i64, link_kind = "mesh", source = @router_7, source_port = 3 : i64, width_bits = 128 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_4, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_0, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_0, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_4, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_5, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_1, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_1, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_5, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_5, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_0, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_0, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_5, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_4, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_1, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @router_1, dest_port = 5 : i64, latency_cycles = 1 : i64, link_kind = "express", source = @router_4, source_port = 5 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_0, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_0, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_1, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_1, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_2, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_2, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_3, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_3, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_4, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_4, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_5, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_5, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_6, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_6, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.noc_link"() {bandwidth = 32 : i64, dest = @l2_bank_7, dest_port = 0 : i64, latency_cycles = 2 : i64, link_kind = "l2_interface", source = @router_7, source_port = 4 : i64, width_bits = 256 : i64} : () -> ()
    "fabric.yield"() : () -> ()
  }) {domain = "scientific_computing", express_link_count = 4 : i64, function_type = () -> (), mesh_cols = 4 : i64, mesh_rows = 2 : i64, shg_id = "D6", sym_name = "D6_scicomp_shg", total_allocated_area_mm2 = 2.250000e+01 : f64, total_area_budget_mm2 = 2.500000e+01 : f64, total_cores = 8 : i64} : () -> ()
}) {domain = "scientific_computing", express_link_count = 4 : i64, mesh_cols = 4 : i64, mesh_rows = 2 : i64, shg_id = "D6", total_allocated_area_mm2 = 2.250000e+01 : f64, total_area_budget_mm2 = 2.500000e+01 : f64, total_cores = 8 : i64} : () -> ()
