#include "loom/SVGen/SVEmitter.h"

#include "loom/Dialect/Fabric/FabricTypes.h"
#include "loom/Mapper/TypeCompat.h"

#include "mlir/IR/BuiltinTypes.h"

#include <cctype>

using namespace loom::svgen;

// --- Indentation ---

void SVEmitter::emitIndent() {
  for (unsigned i = 0; i < indentLevel_; ++i)
    os_ << "  ";
}

// --- File and module structure ---

void SVEmitter::emitFileHeader(llvm::StringRef moduleName) {
  os_ << "// Auto-generated SystemVerilog for module: " << moduleName << "\n";
  os_ << "// Generated by loom SVGen -- do not edit manually.\n";
  os_ << "`default_nettype none\n";
  os_ << "\n";
}

void SVEmitter::emitModuleHeader(llvm::StringRef name,
                                 const std::vector<std::string> &parameters,
                                 const std::vector<SVPort> &ports) {
  os_ << "module " << name;

  if (!parameters.empty()) {
    os_ << " #(\n";
    for (size_t i = 0; i < parameters.size(); ++i) {
      os_ << "  " << parameters[i];
      if (i + 1 < parameters.size())
        os_ << ",";
      os_ << "\n";
    }
    os_ << ")";
  }

  if (!ports.empty()) {
    os_ << " (\n";
    for (size_t i = 0; i < ports.size(); ++i) {
      const auto &port = ports[i];
      os_ << "  " << (port.dir == SVPortDir::Input ? "input  " : "output ")
          << port.typeStr;
      if (!port.typeStr.empty())
        os_ << " ";
      os_ << port.name;
      if (i + 1 < ports.size())
        os_ << ",";
      os_ << "\n";
    }
    os_ << ")";
  }

  os_ << ";\n\n";
}

void SVEmitter::emitModuleFooter(llvm::StringRef name) {
  os_ << "endmodule // " << name << "\n";
  os_ << "\n";
  os_ << "`default_nettype wire\n";
}

// --- Declarations ---

void SVEmitter::emitWire(llvm::StringRef typeStr, llvm::StringRef name) {
  // Emit as plain 'logic' variable (no 'wire' prefix). In SystemVerilog,
  // 'logic' can be used with both continuous assign and procedural
  // (always_comb) assignment, and works for module instance connections.
  // This avoids PROCASSWIRE errors when signals are driven procedurally.
  emitIndent();
  os_ << typeStr;
  if (!typeStr.empty())
    os_ << " ";
  os_ << name << ";\n";
}

void SVEmitter::emitReg(llvm::StringRef typeStr, llvm::StringRef name) {
  emitIndent();
  os_ << "reg " << typeStr;
  if (!typeStr.empty())
    os_ << " ";
  os_ << name << ";\n";
}

void SVEmitter::emitLocalParam(llvm::StringRef typeStr, llvm::StringRef name,
                                llvm::StringRef value) {
  emitIndent();
  os_ << "localparam";
  if (!typeStr.empty())
    os_ << " " << typeStr;
  os_ << " " << name << " = " << value << ";\n";
}

// --- Instance emission ---

void SVEmitter::emitInstance(llvm::StringRef moduleName,
                             llvm::StringRef instanceName,
                             const std::vector<std::string> &paramValues,
                             const std::vector<SVConnection> &connections) {
  emitIndent();
  os_ << moduleName;

  if (!paramValues.empty()) {
    os_ << " #(\n";
    for (size_t i = 0; i < paramValues.size(); ++i) {
      emitIndent();
      os_ << "  " << paramValues[i];
      if (i + 1 < paramValues.size())
        os_ << ",";
      os_ << "\n";
    }
    emitIndent();
    os_ << ")";
  }

  os_ << " " << instanceName << " (\n";

  for (size_t i = 0; i < connections.size(); ++i) {
    emitIndent();
    os_ << "  ." << connections[i].portName << "(" << connections[i].expression
        << ")";
    if (i + 1 < connections.size())
      os_ << ",";
    os_ << "\n";
  }

  emitIndent();
  os_ << ");\n";
}

// --- Assignments and misc ---

void SVEmitter::emitAssign(llvm::StringRef lhs, llvm::StringRef rhs) {
  emitIndent();
  os_ << "assign " << lhs << " = " << rhs << ";\n";
}

void SVEmitter::emitWidthAdapt(llvm::StringRef dstName, llvm::StringRef srcExpr,
                                unsigned srcWidth, unsigned dstWidth,
                                llvm::StringRef waId) {
  if (srcWidth == dstWidth) {
    emitAssign(dstName, srcExpr);
    return;
  }

  emitComment("Fabric width adaptation (" + std::string(waId) + "): " +
              std::to_string(srcWidth) + "b -> " + std::to_string(dstWidth) +
              "b");
  emitComment("See docs/spec-rtl-width-adaptation.md");

  if (srcWidth > dstWidth) {
    // Truncation: take lower dstWidth bits.
    emitRaw("/* verilator lint_off WIDTHTRUNC */\n");
    std::string rhs = std::string(srcExpr) + "[" +
                      std::to_string(dstWidth - 1) + ":0]";
    emitAssign(dstName, rhs);
    emitRaw("/* verilator lint_on WIDTHTRUNC */\n");
  } else {
    // Zero-extension: pad upper bits with 0.
    unsigned pad = dstWidth - srcWidth;
    emitRaw("/* verilator lint_off WIDTHEXPAND */\n");
    std::string rhs = "{" + std::to_string(pad) + "'b0, " +
                      std::string(srcExpr) + "}";
    emitAssign(dstName, rhs);
    emitRaw("/* verilator lint_on WIDTHEXPAND */\n");
  }
}

void SVEmitter::emitTaggedWidthAdapt(llvm::StringRef dstName,
                                      llvm::StringRef srcExpr,
                                      unsigned srcDataW, unsigned srcTagW,
                                      unsigned dstDataW, unsigned dstTagW,
                                      llvm::StringRef waId) {
  unsigned srcTotal = srcDataW + srcTagW;
  unsigned dstTotal = dstDataW + dstTagW;

  // If both data and tag widths match, plain assign.
  if (srcDataW == dstDataW && srcTagW == dstTagW) {
    emitAssign(dstName, srcExpr);
    return;
  }

  emitComment("Fabric tagged width adaptation (" + std::string(waId) +
              "): data " + std::to_string(srcDataW) + "b->" +
              std::to_string(dstDataW) + "b, tag " +
              std::to_string(srcTagW) + "b->" + std::to_string(dstTagW) +
              "b");
  emitComment("See docs/spec-rtl-width-adaptation.md");

  // Build adapted data portion expression.
  std::string srcData = std::string(srcExpr) + "[" +
                        std::to_string(srcDataW - 1) + ":0]";
  std::string dataExpr;
  if (srcDataW == dstDataW) {
    dataExpr = srcData;
  } else if (srcDataW > dstDataW) {
    dataExpr = srcData + "[" + std::to_string(dstDataW - 1) + ":0]";
  } else {
    unsigned pad = dstDataW - srcDataW;
    dataExpr = "{" + std::to_string(pad) + "'b0, " + srcData + "}";
  }

  // Build adapted tag portion expression.
  std::string srcTag = std::string(srcExpr) + "[" +
                       std::to_string(srcDataW + srcTagW - 1) + ":" +
                       std::to_string(srcDataW) + "]";
  std::string tagExpr;
  if (srcTagW == dstTagW) {
    tagExpr = srcTag;
  } else if (srcTagW > dstTagW) {
    tagExpr = srcTag + "[" + std::to_string(dstTagW - 1) + ":0]";
  } else {
    unsigned pad = dstTagW - srcTagW;
    tagExpr = "{" + std::to_string(pad) + "'b0, " + srcTag + "}";
  }

  // Emit the combined adapted assignment with lint waivers.
  std::string lintTag = (srcTotal != dstTotal)
                            ? ((srcTotal > dstTotal) ? "WIDTHTRUNC"
                                                     : "WIDTHEXPAND")
                            : "";
  if (!lintTag.empty())
    emitRaw("/* verilator lint_off " + lintTag + " */\n");
  std::string rhs = "{" + tagExpr + ", " + dataExpr + "}";
  emitAssign(dstName, rhs);
  if (!lintTag.empty())
    emitRaw("/* verilator lint_on " + lintTag + " */\n");
}

void SVEmitter::emitBlankLine() { os_ << "\n"; }

void SVEmitter::emitComment(llvm::StringRef text) {
  emitIndent();
  os_ << "// " << text << "\n";
}

void SVEmitter::emitRaw(llvm::StringRef text) {
  emitIndent();
  os_ << text;
}

void SVEmitter::emitRawNoIndent(llvm::StringRef text) { os_ << text; }

// --- Static naming/type utilities ---

std::string SVEmitter::sanitizeName(llvm::StringRef mlirName) {
  std::string result;
  result.reserve(mlirName.size());
  for (char ch : mlirName) {
    if (std::isalnum(static_cast<unsigned char>(ch)) || ch == '_') {
      result.push_back(ch);
    } else {
      result.push_back('_');
    }
  }
  // Ensure it does not start with a digit.
  if (!result.empty() && std::isdigit(static_cast<unsigned char>(result[0])))
    result.insert(result.begin(), '_');
  return result;
}

unsigned SVEmitter::getTypeWidth(mlir::Type type) {
  if (auto tagged = mlir::dyn_cast<loom::fabric::TaggedType>(type)) {
    unsigned dataW = getDataWidth(tagged.getValueType());
    unsigned tagW = 0;
    if (auto tw = loom::detail::getTagWidth(tagged.getTagType()))
      tagW = *tw;
    return dataW + tagW;
  }
  if (auto w = loom::detail::getScalarWidth(type))
    return *w;
  if (mlir::isa<mlir::MemRefType>(type)) {
    if (auto w = loom::detail::getMemRefElementWidth(type))
      return *w;
  }
  return 32; // fallback
}

unsigned SVEmitter::getDataWidth(mlir::Type type) {
  if (auto tagged = mlir::dyn_cast<loom::fabric::TaggedType>(type))
    return getDataWidth(tagged.getValueType());
  if (auto w = loom::detail::getScalarWidth(type))
    return *w;
  return 32; // fallback
}

unsigned SVEmitter::getTagWidth(mlir::Type type) {
  if (auto tagged = mlir::dyn_cast<loom::fabric::TaggedType>(type)) {
    if (auto tw = loom::detail::getTagWidth(tagged.getTagType()))
      return *tw;
  }
  return 0;
}

std::string SVEmitter::typeToSV(mlir::Type type) {
  unsigned width = getTypeWidth(type);
  if (width <= 1)
    return "logic";
  return "logic [" + std::to_string(width - 1) + ":0]";
}

std::string SVEmitter::bitRange(unsigned width) {
  if (width <= 1)
    return "";
  return "[" + std::to_string(width - 1) + ":0]";
}
