#include "fcc/Conversion/HostCodeGen.h"
#include "fcc/Conversion/Passes.h"

#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"

#include "circt/Dialect/Handshake/HandshakeOps.h"

#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

#include <string>

using namespace mlir;

namespace {

// Information about an accelerated function extracted from the MLIR module.
struct AccelFuncInfo {
  std::string name;
  unsigned numMemRegions = 0; // number of memref arguments
  unsigned numScalarArgs = 0; // number of scalar arguments
  // Argument layout: which arg indices are memrefs vs scalars
  SmallVector<bool> isMemrefArg; // true = memref, false = scalar
};

// Analyze the module to find functions that were converted to handshake.func.
// These are the accelerated functions whose calls need MMIO driver replacement.
static void findAccelFuncs(ModuleOp module,
                           SmallVectorImpl<AccelFuncInfo> &accelFuncs) {
  // Look for handshake.func operations (DFG-converted functions)
  module.walk([&](circt::handshake::FuncOp hsfunc) {
    AccelFuncInfo info;
    info.name = hsfunc.getName().str();

    // Also look at the original func.func (if it still exists with
    // fcc.dfg_candidate) to understand argument types
    module.walk([&](func::FuncOp origFunc) {
      if (origFunc.getName() != info.name)
        return;
      auto funcType = origFunc.getFunctionType();
      for (unsigned i = 0; i < funcType.getNumInputs(); i++) {
        Type argTy = funcType.getInput(i);
        if (isa<MemRefType>(argTy)) {
          info.isMemrefArg.push_back(true);
          info.numMemRegions++;
        } else {
          info.isMemrefArg.push_back(false);
          info.numScalarArgs++;
        }
      }
    });

    // If original func was already removed, infer from handshake.func
    // signature. For MVP, fall back to a reasonable default.
    if (info.isMemrefArg.empty()) {
      // Inspect the handshake.func arguments. Handshake functions have
      // flattened arguments; we use the dfg metadata if available.
      if (auto attr =
              hsfunc->getAttrOfType<IntegerAttr>("fcc.dfg_estimated_mem"))
        info.numMemRegions = attr.getInt();
      if (info.numMemRegions == 0)
        info.numMemRegions = 3; // default for vecadd: a, b, c
      info.numScalarArgs = 1;   // default for vecadd: n
    }

    accelFuncs.push_back(info);
  });
}

// Generate the fcc_accel.h header content.
static std::string generateAccelHeader() {
  std::string header;
  llvm::raw_string_ostream os(header);

  os << "// fcc_accel.h - thin MMIO driver for fcc accelerator\n";
  os << "// Auto-generated by fcc host code generator\n";
  os << "#ifndef FCC_ACCEL_H\n";
  os << "#define FCC_ACCEL_H\n";
  os << "\n";
  os << "#include <stdint.h>\n";
  os << "#include <stddef.h>\n";
  os << "\n";
  os << "// Base address of CGRA accelerator MMIO region\n";
  os << "#define FCC_ACCEL_BASE  0x40000000UL\n";
  os << "\n";
  os << "// Register offsets\n";
  os << "#define FCC_REG_STATUS      0x00\n";
  os << "#define FCC_REG_CONTROL     0x04\n";
  os << "#define FCC_REG_CONFIG_ADDR 0x08\n";
  os << "#define FCC_REG_CONFIG_DATA 0x0C\n";
  os << "#define FCC_REG_MEM_BASE(n) (0x20 + (n) * 0x10)\n";
  os << "#define FCC_REG_MEM_SIZE(n) (0x24 + (n) * 0x10)\n";
  os << "#define FCC_REG_ARG(n)      (0x80 + (n) * 0x08)\n";
  os << "#define FCC_REG_CYCLE_COUNT 0xF0\n";
  os << "#define FCC_REG_MAX_MEM     8\n";
  os << "#define FCC_REG_MAX_ARG     8\n";
  os << "\n";
  os << "// Status register bits\n";
  os << "#define FCC_STATUS_BUSY  (1 << 0)\n";
  os << "#define FCC_STATUS_DONE  (1 << 1)\n";
  os << "#define FCC_STATUS_ERROR (1 << 2)\n";
  os << "\n";
  os << "// Control register bits\n";
  os << "#define FCC_CTRL_START   (1 << 0)\n";
  os << "#define FCC_CTRL_RESET   (1 << 1)\n";
  os << "\n";
  os << "static volatile uint32_t *fcc_mmio = "
        "(volatile uint32_t *)FCC_ACCEL_BASE;\n";
  os << "\n";
  os << "static inline void fcc_write(unsigned offset, uint32_t val) {\n";
  os << "    fcc_mmio[offset / 4] = val;\n";
  os << "}\n";
  os << "\n";
  os << "static inline uint32_t fcc_read(unsigned offset) {\n";
  os << "    return fcc_mmio[offset / 4];\n";
  os << "}\n";
  os << "\n";
  os << "static inline void fcc_accel_init(void) {\n";
  os << "    fcc_write(FCC_REG_CONTROL, FCC_CTRL_RESET);\n";
  os << "    fcc_write(FCC_REG_CONTROL, 0);\n";
  os << "}\n";
  os << "\n";
  os << "static inline void fcc_accel_load_config("
        "const uint32_t *words, unsigned count) {\n";
  os << "    for (unsigned i = 0; i < count; i++) {\n";
  os << "        fcc_write(FCC_REG_CONFIG_ADDR, i);\n";
  os << "        fcc_write(FCC_REG_CONFIG_DATA, words[i]);\n";
  os << "    }\n";
  os << "}\n";
  os << "\n";
  os << "static inline void fcc_accel_set_mem_region("
        "unsigned id, void *addr, size_t size) {\n";
  os << "    fcc_write(FCC_REG_MEM_BASE(id), (uint32_t)(uintptr_t)addr);\n";
  os << "    fcc_write(FCC_REG_MEM_SIZE(id), (uint32_t)size);\n";
  os << "}\n";
  os << "\n";
  os << "static inline void fcc_accel_set_arg("
        "unsigned id, uint64_t value) {\n";
  os << "    fcc_write(FCC_REG_ARG(id), (uint32_t)value);\n";
  os << "}\n";
  os << "\n";
  os << "static inline void fcc_accel_launch(void) {\n";
  os << "    fcc_write(FCC_REG_CONTROL, FCC_CTRL_START);\n";
  os << "}\n";
  os << "\n";
  os << "static inline int fcc_accel_wait(void) {\n";
  os << "    while (1) {\n";
  os << "        uint32_t status = fcc_read(FCC_REG_STATUS);\n";
  os << "        if (status & FCC_STATUS_ERROR) return -1;\n";
  os << "        if (status & FCC_STATUS_DONE) return 0;\n";
  os << "    }\n";
  os << "}\n";
  os << "\n";
  os << "static inline uint64_t fcc_accel_cycle_count(void) {\n";
  os << "    return (uint64_t)fcc_read(FCC_REG_CYCLE_COUNT);\n";
  os << "}\n";
  os << "\n";
  os << "#endif\n";

  return header;
}

// Generate the host C source that replaces accelerated calls with MMIO driver.
static std::string generateHostSource(const std::string &originalSource,
                                      ArrayRef<AccelFuncInfo> accelFuncs) {
  std::string source;
  llvm::raw_string_ostream os(source);

  os << "// Host driver for fcc accelerated program\n";
  os << "// Auto-generated by fcc host code generator\n";
  if (!originalSource.empty())
    os << "// Original source: " << originalSource << "\n";
  os << "//\n";
  os << "// Accelerated function(s):\n";
  for (const auto &f : accelFuncs)
    os << "//   " << f.name << " (" << f.numMemRegions << " mem regions, "
       << f.numScalarArgs << " scalar args)\n";
  os << "//\n";
  os << "// This file can be cross-compiled for RISC-V:\n";
  os << "//   riscv64-linux-gnu-gcc -static -o host.elf "
     << "this_file.c\n";
  os << "\n";
  os << "#include <stdio.h>\n";
  os << "#include <stdlib.h>\n";
  os << "#include \"fcc_accel.h\"\n";
  os << "\n";

  // Generate an accel-invoke wrapper for each accelerated function
  for (const auto &func : accelFuncs) {
    os << "// Accelerator invocation replacing: " << func.name << "(...)\n";
    os << "//\n";
    os << "// Call pattern: fcc_invoke_" << func.name << "(";

    // Build parameter list
    unsigned memIdx = 0;
    unsigned scalarIdx = 0;
    bool first = true;
    for (unsigned i = 0; i < func.isMemrefArg.size(); i++) {
      if (!first)
        os << ", ";
      first = false;
      if (func.isMemrefArg[i]) {
        os << "void *mem" << memIdx << ", size_t mem" << memIdx << "_size";
        memIdx++;
        // Extra comma for size param handled by next iteration check
        first = false;
      } else {
        os << "uint64_t arg" << scalarIdx;
        scalarIdx++;
      }
    }
    os << ")\n";

    // Generate the wrapper function body
    os << "static inline void fcc_invoke_" << func.name << "(";
    memIdx = 0;
    scalarIdx = 0;
    first = true;
    for (unsigned i = 0; i < func.isMemrefArg.size(); i++) {
      if (!first)
        os << ", ";
      first = false;
      if (func.isMemrefArg[i]) {
        os << "void *mem" << memIdx << ", size_t mem" << memIdx << "_size";
        memIdx++;
        first = false;
      } else {
        os << "uint64_t arg" << scalarIdx;
        scalarIdx++;
      }
    }
    // If we had no arg info, generate a generic version
    if (func.isMemrefArg.empty()) {
      // Generic version based on counts
      for (unsigned i = 0; i < func.numMemRegions; i++) {
        if (!first)
          os << ", ";
        first = false;
        os << "void *mem" << i << ", size_t mem" << i << "_size";
      }
      for (unsigned i = 0; i < func.numScalarArgs; i++) {
        if (!first)
          os << ", ";
        first = false;
        os << "uint64_t arg" << i;
      }
    }
    os << ") {\n";

    os << "    fcc_accel_init();\n";
    os << "\n";
    os << "    // TODO: load config from config.bin when available\n";
    os << "    // fcc_accel_load_config(config_words, config_count);\n";
    os << "\n";

    // Set up memory regions
    unsigned totalMem =
        func.isMemrefArg.empty()
            ? func.numMemRegions
            : static_cast<unsigned>(
                  llvm::count(func.isMemrefArg, true));
    for (unsigned i = 0; i < totalMem; i++) {
      os << "    fcc_accel_set_mem_region(" << i << ", mem" << i << ", mem"
         << i << "_size);\n";
    }
    os << "\n";

    // Set scalar arguments
    unsigned totalScalar =
        func.isMemrefArg.empty()
            ? func.numScalarArgs
            : static_cast<unsigned>(
                  llvm::count(func.isMemrefArg, false));
    for (unsigned i = 0; i < totalScalar; i++) {
      os << "    fcc_accel_set_arg(" << i << ", arg" << i << ");\n";
    }
    os << "\n";

    os << "    fcc_accel_launch();\n";
    os << "    fcc_accel_wait();\n";
    os << "}\n\n";
  }

  // Generate a sample main that shows the invocation pattern
  os << "// Sample main() showing accelerator invocation.\n";
  os << "// Adapt this to your specific application.\n";
  os << "int main() {\n";

  if (!accelFuncs.empty()) {
    const auto &f = accelFuncs[0];
    os << "    // Example for " << f.name << ":\n";
    os << "    // Replace with actual data arrays and sizes.\n";
    os << "\n";

    // For vecadd-like kernels, generate a concrete example
    if (f.name == "vecadd" && f.numMemRegions == 3) {
      os << "    int a[4] = {1, 2, 3, 4};\n";
      os << "    int b[4] = {5, 6, 7, 8};\n";
      os << "    int c[4] = {0, 0, 0, 0};\n";
      os << "    int golden[4] = {6, 8, 10, 12};\n";
      os << "\n";
      os << "    // Invoke accelerator (replaces: vecadd(a, b, c, 4))\n";
      os << "    fcc_invoke_vecadd(\n";
      os << "        a, 4 * sizeof(int),\n";
      os << "        b, 4 * sizeof(int),\n";
      os << "        c, 4 * sizeof(int),\n";
      os << "        4  // n\n";
      os << "    );\n";
      os << "\n";
      os << "    // Verification\n";
      os << "    int pass = 1;\n";
      os << "    for (int i = 0; i < 4; i++) {\n";
      os << "        if (c[i] != golden[i]) {\n";
      os << "            printf(\"FAIL: c[%d] = %d, expected %d\\n\",\n";
      os << "                   i, c[i], golden[i]);\n";
      os << "            pass = 0;\n";
      os << "        }\n";
      os << "    }\n";
      os << "    if (pass) printf(\"PASS\\n\");\n";
      os << "    return pass ? 0 : 1;\n";
    } else {
      // Generic placeholder
      for (unsigned i = 0; i < f.numMemRegions; i++) {
        os << "    int mem" << i << "_data[16] = {0};\n";
      }
      os << "\n";
      os << "    fcc_invoke_" << f.name << "(";
      bool first = true;
      for (unsigned i = 0; i < f.numMemRegions; i++) {
        if (!first)
          os << ", ";
        first = false;
        os << "mem" << i << "_data, sizeof(mem" << i << "_data)";
      }
      for (unsigned i = 0; i < f.numScalarArgs; i++) {
        if (!first)
          os << ", ";
        first = false;
        os << "16";
      }
      os << ");\n";
      os << "\n";
      os << "    printf(\"Accelerator invocation complete\\n\");\n";
      os << "    return 0;\n";
    }
  } else {
    os << "    printf(\"No accelerated functions found\\n\");\n";
    os << "    return 0;\n";
  }

  os << "}\n";

  return source;
}

struct HostCodeGenPass
    : public PassWrapper<HostCodeGenPass, OperationPass<ModuleOp>> {
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(HostCodeGenPass)

  std::string outputPath;
  std::string originalSource;

  HostCodeGenPass(const std::string &outputPath,
                  const std::string &originalSource)
      : outputPath(outputPath), originalSource(originalSource) {}

  StringRef getArgument() const override { return "fcc-host-codegen"; }
  StringRef getDescription() const override {
    return "Generate host C source with MMIO driver calls for accelerated "
           "functions";
  }

  void runOnOperation() override {
    auto module = getOperation();

    // Find accelerated functions
    SmallVector<AccelFuncInfo> accelFuncs;
    findAccelFuncs(module, accelFuncs);

    if (accelFuncs.empty()) {
      llvm::outs() << "fcc: no accelerated functions found; "
                      "skipping host code generation\n";
      return;
    }

    llvm::outs() << "fcc: generating host code for " << accelFuncs.size()
                 << " accelerated function(s)\n";

    // Generate fcc_accel.h alongside the host source
    llvm::SmallString<256> headerPath(outputPath);
    llvm::sys::path::remove_filename(headerPath);
    llvm::sys::path::append(headerPath, "fcc_accel.h");

    {
      std::error_code ec;
      llvm::raw_fd_ostream os(headerPath, ec);
      if (ec) {
        llvm::errs() << "fcc: cannot write " << headerPath << ": "
                     << ec.message() << "\n";
        signalPassFailure();
        return;
      }
      os << generateAccelHeader();
      llvm::outs() << "fcc: wrote " << headerPath << "\n";
    }

    // Generate the host C source
    {
      std::error_code ec;
      llvm::raw_fd_ostream os(outputPath, ec);
      if (ec) {
        llvm::errs() << "fcc: cannot write " << outputPath << ": "
                     << ec.message() << "\n";
        signalPassFailure();
        return;
      }
      os << generateHostSource(originalSource, accelFuncs);
      llvm::outs() << "fcc: wrote " << outputPath << "\n";
    }
  }
};

} // namespace

std::unique_ptr<Pass>
fcc::createHostCodeGenPass(const std::string &outputPath,
                           const std::string &originalSource) {
  return std::make_unique<HostCodeGenPass>(outputPath, originalSource);
}
