// RUN: loom %s | FileCheck %s

// Shared reduction-class ADG candidate. It is a reusable, regular hardware
// template with stream, integer ALU, sync, and memory resources; it is not a
// hardware graph generated by copying a single software DFG node-for-node.
// The topology is explicit and graph-based, with no mesh-coordinate assumption.
// CHECK-LABEL: fabric.module @shared_reduction_adg
fabric.module @shared_reduction_adg(%mgr : memref<?x!fabric.bits<32>>,
                                    %i64a : !fabric.bits<64>,
                                    %i64b : !fabric.bits<64>,
                                    %i64c : !fabric.bits<64>,
                                    %i32a : !fabric.bits<32>,
                                    %i32b : !fabric.bits<32>,
                                    %i32c : !fabric.bits<32>,
                                    %ctrl : !fabric.bits<0>) {
  // CHECK: fabric.op [@dataflow.stream]
  fabric.pe [spatial] (%pa = %i64a : !fabric.bits<64>,
                    %pb = %i64b : !fabric.bits<64>,
                    %pc = %i64c : !fabric.bits<64>) -> !fabric.bits<64> {
    fabric.fu(%fa = %pa : !fabric.bits<64>,
              %fb = %pb : !fabric.bits<64>,
              %fc = %pc : !fabric.bits<64>) -> () {
      %idx, %rwc = fabric.op [@dataflow.stream] (%fa, %fb, %fc)
                   {hw_params = [{step_op = ["+="], cont_cond = ["<"]}],
                    sw_configs = {step_op = "+=", cont_cond = "<"}}
                   : (!fabric.bits<64>, !fabric.bits<64>, !fabric.bits<64>)
                     -> (!fabric.bits<64>, !fabric.bits<1>)
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>,
                    %pc = %i32c : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@dataflow.carry]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %init = %pb : !fabric.bits<32>,
              %next = %pc : !fabric.bits<32>) -> () {
      %carried = fabric.op [@dataflow.carry] (%cond, %init, %next)
                 : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      fabric.yield
    }
    // CHECK: fabric.op [@dataflow.invariant]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %value = %pb : !fabric.bits<32>) -> () {
      %stable = fabric.op [@dataflow.invariant] (%cond, %value)
                : (!fabric.bits<1>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
    // CHECK: fabric.op [@arith.addi]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %sum = fabric.op [@arith.addi] (%lhs, %rhs)
             : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pc = %ctrl : !fabric.bits<0>) -> !fabric.bits<0> {
    fabric.fu(%fc = %pc : !fabric.bits<0>) -> () {
      // CHECK: fabric.op [@dataflow.sync]
      %done = fabric.op [@dataflow.sync] (%fc)
              {sw_configs = {bitmask = "1"}}
              : (!fabric.bits<0>) -> !fabric.bits<0>
      fabric.yield
    }
  }
  // CHECK: fabric.mem [spatial]
  %data, %done = fabric.mem [spatial] mgr(%mgr) load(%i32a, %ctrl)
        [{load_group_size = 1 : i32, store_group_size = 0 : i32}]
        : (memref<?x!fabric.bits<32>>, !fabric.bits<32>, !fabric.bits<0>)
        -> (!fabric.bits<32>, !fabric.bits<0>)
  fabric.yield
}
