// RUN: loom %s | FileCheck %s

// Shared reduction-class ADG candidate. It is a reusable, regular hardware
// template with stream, integer ALU, sync, and memory resources; it is not a
// hardware graph generated by copying a single software DFG node-for-node.
// The topology is explicit and graph-based, with no mesh-coordinate assumption.
// CHECK-LABEL: fabric.module @shared_reduction_adg
fabric.module @shared_reduction_adg(%mgr : memref<?x!fabric.bits<32>>,
                                    %i64a : !fabric.bits<64>,
                                    %i64b : !fabric.bits<64>,
                                    %i64c : !fabric.bits<64>,
                                    %i32a : !fabric.bits<32>,
                                    %i32b : !fabric.bits<32>,
                                    %i32c : !fabric.bits<32>,
                                    %i32d : !fabric.bits<32>,
                                    %ctrl : !fabric.bits<0>) {
  // CHECK: fabric.op [@dataflow.stream]
  %idx = fabric.pe [spatial] (%pa = %i64a : !fabric.bits<64> to !fabric.bits<32>,
                           %pb = %i64b : !fabric.bits<64> to !fabric.bits<32>,
                           %pc = %i64c : !fabric.bits<64> to !fabric.bits<32>,
                           %pd = %data0 : !fabric.bits<32>,
                           %pi = %i32a : !fabric.bits<32>) -> !fabric.bits<32> {
    fabric.fu(%fa = %pa : !fabric.bits<32>,
              %fb = %pb : !fabric.bits<32>,
              %fc = %pc : !fabric.bits<32>,
              %data = %pd : !fabric.bits<32>,
              %init = %pi : !fabric.bits<32>) -> !fabric.bits<32> {
      %idx, %rwc = fabric.op [@dataflow.stream] (%fa, %fb, %fc)
                   {hw_params = [{step_op = ["+="], cont_cond = ["<"]}],
                    sw_configs = {step_op = "+=", cont_cond = "<"}}
                   : (!fabric.bits<32>, !fabric.bits<32>, !fabric.bits<32>)
                     -> (!fabric.bits<32>, !fabric.bits<1>)
      %carried = fabric.op [@dataflow.carry] (%rwc, %init, %sum)
                 : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      %sum = fabric.op [@arith.addi] (%data, %carried)
             : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield %idx : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>,
                    %pc = %i32c : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@dataflow.carry]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %init = %pb : !fabric.bits<32>,
              %next = %pc : !fabric.bits<32>) -> () {
      %carried = fabric.op [@dataflow.carry] (%cond, %init, %next)
                 : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      fabric.yield
    }
    // CHECK: fabric.op [@dataflow.carry]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %init = %pb : !fabric.bits<32>,
              %next = %pc : !fabric.bits<32>) -> () {
      %carried = fabric.op [@dataflow.carry] (%cond, %init, %next)
                 : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@dataflow.invariant]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %value = %pb : !fabric.bits<32>) -> () {
      %stable = fabric.op [@dataflow.invariant] (%cond, %value)
                : (!fabric.bits<1>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
    // CHECK: fabric.op [@dataflow.invariant]
    fabric.fu(%cond = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %value = %pb : !fabric.bits<32>) -> () {
      %stable = fabric.op [@dataflow.invariant] (%cond, %value)
                : (!fabric.bits<1>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.addi]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %sum = fabric.op [@arith.addi] (%lhs, %rhs)
             : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.addf]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %sum = fabric.op [@arith.addf] (%lhs, %rhs)
             : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.subf]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %diff = fabric.op [@arith.subf] (%lhs, %rhs)
              : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.mulf]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %product = fabric.op [@arith.mulf] (%lhs, %rhs)
                 : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.muli]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %product = fabric.op [@arith.muli] (%lhs, %rhs)
                 : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.shrui]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %shifted = fabric.op [@arith.shrui] (%lhs, %rhs)
                 : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.shli]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %shifted = fabric.op [@arith.shli] (%lhs, %rhs)
                 : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.andi]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %masked = fabric.op [@arith.andi] (%lhs, %rhs)
                : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.ori]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %combined = fabric.op [@arith.ori] (%lhs, %rhs)
                  : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.xori]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %combined = fabric.op [@arith.xori] (%lhs, %rhs)
                  : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>,
                    %pc = %i32c : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@llvm.intr.fmuladd]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>,
              %acc = %pc : !fabric.bits<32>) -> () {
      %mac = fabric.op [@llvm.intr.fmuladd] (%lhs, %rhs, %acc)
             : (!fabric.bits<32>, !fabric.bits<32>, !fabric.bits<32>)
               -> !fabric.bits<32>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>,
                    %pc = %i32c : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@llvm.intr.fshl]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>,
              %amount = %pc : !fabric.bits<32>) -> !fabric.bits<32> {
      %rotated = fabric.op [@llvm.intr.fshl] (%lhs, %rhs, %amount)
                 : (!fabric.bits<32>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      fabric.yield %rotated : !fabric.bits<32>
    }
    // CHECK: fabric.op [@llvm.intr.fshl]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>,
              %amount = %pc : !fabric.bits<32>) -> !fabric.bits<32> {
      %rotated = fabric.op [@llvm.intr.fshl] (%lhs, %rhs, %amount)
                 : (!fabric.bits<32>, !fabric.bits<32>, !fabric.bits<32>)
                   -> !fabric.bits<32>
      fabric.yield %rotated : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@llvm.intr.abs]
    fabric.fu(%value = %pa : !fabric.bits<32>) -> !fabric.bits<32> {
      %abs = fabric.op [@llvm.intr.abs] (%value)
             : (!fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield %abs : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@llvm.intr.bswap]
    fabric.fu(%value = %pa : !fabric.bits<32>) -> !fabric.bits<32> {
      %swapped = fabric.op [@llvm.intr.bswap] (%value)
                 : (!fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield %swapped : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pa = %i64a : !fabric.bits<64>) -> !fabric.bits<64> {
    // CHECK: fabric.op [@llvm.zext]
    fabric.fu(%value = %pa : !fabric.bits<64> to !fabric.bits<32>)
        -> !fabric.bits<64> {
      %wide = fabric.op [@llvm.zext] (%value)
              : (!fabric.bits<32>) -> !fabric.bits<64>
      fabric.yield %wide : !fabric.bits<64>
    }
  }
  fabric.pe [spatial] (%pa = %i64a : !fabric.bits<64>) -> !fabric.bits<64> {
    // CHECK: fabric.op [@llvm.trunc]
    fabric.fu(%value = %pa : !fabric.bits<64>) -> !fabric.bits<64> {
      %narrow = fabric.op [@llvm.trunc] (%value)
                : (!fabric.bits<64>) -> !fabric.bits<64>
      fabric.yield %narrow : !fabric.bits<64>
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@llvm.uitofp]
    fabric.fu(%value = %pa : !fabric.bits<32>) -> !fabric.bits<32> {
      %fp = fabric.op [@llvm.uitofp] (%value)
            : (!fabric.bits<32>) -> !fabric.bits<32>
      fabric.yield %fp : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.cmpf]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %pred = fabric.op [@arith.cmpf] (%lhs, %rhs)
              {hw_params = [{predicate = ["oeq", "ogt", "ugt", "ule"]}]}
              : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<1>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.cmpi]
    fabric.fu(%lhs = %pa : !fabric.bits<32>,
              %rhs = %pb : !fabric.bits<32>) -> () {
      %pred = fabric.op [@arith.cmpi] (%lhs, %rhs)
              {hw_params = [{predicate = ["eq", "ne", "slt", "sgt", "ult", "ule"]}]}
              : (!fabric.bits<32>, !fabric.bits<32>) -> !fabric.bits<1>
      fabric.yield
    }
  }
  fabric.pe [spatial] (%pa = %i32a : !fabric.bits<32>,
                    %pb = %i32b : !fabric.bits<32>,
                    %pc = %i32c : !fabric.bits<32>) -> !fabric.bits<32> {
    // CHECK: fabric.op [@arith.select]
    fabric.fu(%sel = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %when_true = %pb : !fabric.bits<32>,
              %when_false = %pc : !fabric.bits<32>) -> !fabric.bits<32> {
      %selected = fabric.op [@arith.select] (%sel, %when_true, %when_false)
                  : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                    -> !fabric.bits<32>
      fabric.yield %selected : !fabric.bits<32>
    }
    // CHECK: fabric.op [@arith.select]
    fabric.fu(%sel = %pa : !fabric.bits<32> to !fabric.bits<1>,
              %when_true = %pb : !fabric.bits<32>,
              %when_false = %pc : !fabric.bits<32>) -> !fabric.bits<32> {
      %selected = fabric.op [@arith.select] (%sel, %when_true, %when_false)
                  : (!fabric.bits<1>, !fabric.bits<32>, !fabric.bits<32>)
                    -> !fabric.bits<32>
      fabric.yield %selected : !fabric.bits<32>
    }
  }
  fabric.pe [spatial] (%pc = %done0 : !fabric.bits<0>) -> !fabric.bits<0> {
    fabric.fu(%fc = %pc : !fabric.bits<0>) -> !fabric.bits<0> {
      // CHECK: fabric.op [@dataflow.sync]
      %done = fabric.op [@dataflow.sync] (%fc)
              {sw_configs = {bitmask = "1"}}
              : (!fabric.bits<0>) -> !fabric.bits<0>
      fabric.yield %done : !fabric.bits<0>
    }
  }
  // CHECK: fabric.mem [spatial]
  %data0, %done0, %data1, %done1, %data2, %done2, %data3, %done3, %store_done0, %store_done1 =
      fabric.mem [spatial] mgr(%mgr) load(%idx, %ctrl, %i32b, %ctrl,
                                          %i32c, %ctrl, %i32d, %ctrl)
                            store(%i32a, %i32b, %ctrl,
                                  %i32c, %i32d, %ctrl)
        [{load_group_size = 4 : i32, store_group_size = 2 : i32}]
        : (memref<?x!fabric.bits<32>>, !fabric.bits<32>, !fabric.bits<0>,
           !fabric.bits<32>, !fabric.bits<0>,
           !fabric.bits<32>, !fabric.bits<0>,
           !fabric.bits<32>, !fabric.bits<0>,
           !fabric.bits<32>, !fabric.bits<32>, !fabric.bits<0>,
           !fabric.bits<32>, !fabric.bits<32>, !fabric.bits<0>)
        -> (!fabric.bits<32>, !fabric.bits<0>,
            !fabric.bits<32>, !fabric.bits<0>,
            !fabric.bits<32>, !fabric.bits<0>,
            !fabric.bits<32>, !fabric.bits<0>,
            !fabric.bits<0>,
            !fabric.bits<0>)
  fabric.yield
}
