add_subdirectory(loom)
add_subdirectory(loom-alignment-test)
add_subdirectory(loom-candidate-dump)
add_subdirectory(loom-config-test)
add_subdirectory(loom-cost-test)
add_subdirectory(loom-coverage-test)
add_subdirectory(loom-hwsg-test)
add_subdirectory(loom-parallel-test)
add_subdirectory(loom-synth-base-test)
add_subdirectory(loom-synth-config-test)
add_subdirectory(loom-template-dump)
