add_subdirectory(loom)
add_subdirectory(loom-adg)
add_subdirectory(loom-application-build)
add_subdirectory(loom-cc)
add_subdirectory(loom-lower)
add_subdirectory(loom-payload)
add_subdirectory(loom-pre-mapping)
add_subdirectory(loom-raise)
add_subdirectory(loom-raise-opt)
add_subdirectory(loom-config-test)
add_subdirectory(loom-dfg-sim)
add_subdirectory(loom-dfg-run)
add_subdirectory(loom-dse)
add_subdirectory(loom-gem5-spatial-engine)
add_subdirectory(loom-system-run)
add_subdirectory(loom-tech-map)
add_subdirectory(loom-backend-tool-catalog)
if(LOOM_HAVE_CIRCT)
  add_subdirectory(loom-hw-probe)
endif()
