add_subdirectory(loom)
add_subdirectory(loom-cc)
add_subdirectory(loom-raise)
add_subdirectory(loom-raise-opt)
add_subdirectory(loom-alignment-test)
add_subdirectory(loom-candidate-dump)
add_subdirectory(loom-config-test)
add_subdirectory(loom-cost-test)
add_subdirectory(loom-coverage-test)
add_subdirectory(loom-hwsg-test)
add_subdirectory(loom-parallel-test)
add_subdirectory(loom-synth-base-test)
add_subdirectory(loom-synth-config-test)
add_subdirectory(loom-synth-fu-dump)
add_subdirectory(loom-synth-verifier-test)
add_subdirectory(loom-template-dump)
