#include "SVGenInternal.h"

#include "fcc/SVGen/SVEmitter.h"
#include "fcc/SVGen/SVModuleRegistry.h"

#include "fcc/Dialect/Fabric/FabricOps.h"
#include "fcc/Dialect/Fabric/FabricTypes.h"
#include "fcc/Mapper/TypeCompat.h"

#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/SymbolTable.h"

#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"

#include <string>
#include <vector>

namespace fcc {
namespace svgen {

namespace {

/// Collect FU info from a PE body.
struct FUInfo {
  std::string fuSymName;
  std::string svModuleName; // "fu_<name>"
  unsigned numInputs = 0;
  unsigned numOutputs = 0;
  unsigned configBits = 0;
  fcc::fabric::FunctionUnitOp fuOp;
};

/// Compute config bits for a single FU body op.
static unsigned getBodyOpConfigBits(mlir::Operation &op,
                                    unsigned dataWidth) {
  if (auto muxOp = mlir::dyn_cast<fcc::fabric::MuxOp>(op)) {
    unsigned numMuxIn = muxOp.getInputs().size();
    unsigned selBits = numMuxIn > 1 ? llvm::Log2_32_Ceil(numMuxIn) : 0;
    return selBits + 2; // sel + discard + disconnect
  }
  llvm::StringRef opName = op.getName().getStringRef();
  if (opName == "arith.cmpi" || opName == "arith.cmpf")
    return 4;
  if (opName == "handshake.constant")
    return dataWidth;
  if (opName == "handshake.join")
    return op.getNumOperands(); // NUM_IN bits for join mask
  if (opName == "dataflow.stream")
    return 5;
  return 0;
}

/// Compute total config bits for a FunctionUnitOp body.
static unsigned computeFUBodyConfigBits(fcc::fabric::FunctionUnitOp fuOp) {
  auto fnType = fuOp.getFunctionType();
  unsigned dataWidth = 32;
  if (fnType.getNumInputs() > 0)
    dataWidth = SVEmitter::getDataWidth(fnType.getInput(0));
  else if (fnType.getNumResults() > 0)
    dataWidth = SVEmitter::getDataWidth(fnType.getResult(0));

  unsigned cfgBits = 0;
  for (auto &op : fuOp.getBody().front().getOperations()) {
    if (mlir::isa<fcc::fabric::YieldOp>(op))
      continue;
    cfgBits += getBodyOpConfigBits(op, dataWidth);
  }
  return cfgBits;
}

static std::vector<FUInfo> collectFUs(mlir::Block &peBody) {
  std::vector<FUInfo> fus;

  // Build a map of FunctionUnitOp definitions reachable from the enclosing
  // MLIR module so that fabric.instance ops can resolve shared FU defs.
  llvm::DenseMap<llvm::StringRef, fcc::fabric::FunctionUnitOp> fuDefMap;
  if (mlir::Operation *parentOp = peBody.getParentOp()) {
    if (auto parentModule = parentOp->getParentOfType<mlir::ModuleOp>()) {
      parentModule->walk([&](fcc::fabric::FunctionUnitOp fuDef) {
        fuDefMap[fuDef.getSymName()] = fuDef;
      });
    }
  }

  for (auto &op : peBody.getOperations()) {
    if (auto fuOp = mlir::dyn_cast<fcc::fabric::FunctionUnitOp>(op)) {
      FUInfo info;
      info.fuSymName = fuOp.getSymName().str();
      info.svModuleName =
          "fu_" + SVEmitter::sanitizeName(fuOp.getSymName());
      auto fnType = fuOp.getFunctionType();
      info.numInputs = fnType.getNumInputs();
      info.numOutputs = fnType.getNumResults();
      info.fuOp = fuOp;

      // Count FU internal config bits (all configurable body ops).
      info.configBits = computeFUBodyConfigBits(fuOp);

      fus.push_back(std::move(info));
      continue;
    }

    // Handle fabric.instance referencing a shared FunctionUnitOp definition.
    if (auto instOp = mlir::dyn_cast<fcc::fabric::InstanceOp>(op)) {
      llvm::StringRef refName = instOp.getModule().getValue();
      auto it = fuDefMap.find(refName);
      if (it == fuDefMap.end())
        continue; // Not a FU instance (could be a PE or SW instance).
      fcc::fabric::FunctionUnitOp fuOp = it->second;

      FUInfo info;
      info.fuSymName = instOp.getSymName().value_or(refName).str();
      info.svModuleName =
          "fu_" + SVEmitter::sanitizeName(fuOp.getSymName());
      auto fnType = fuOp.getFunctionType();
      info.numInputs = fnType.getNumInputs();
      info.numOutputs = fnType.getNumResults();
      info.fuOp = fuOp;
      info.configBits = computeFUBodyConfigBits(fuOp);

      fus.push_back(std::move(info));
    }
  }
  return fus;
}

/// Helper: unsigned to string.
static std::string u2s(unsigned v) { return std::to_string(v); }

/// Helper: signed to string.
static std::string s2s(int64_t v) { return std::to_string(v); }

} // namespace

// =================================================================
// generateSpatialPE
// =================================================================
//
// Generated wrapper module architecture:
//
//   pe_<name> (wrapper, generated by this C++)
//     +-- fabric_spatial_pe (container, pre-written)
//     |     handles: config loading, field extraction, mux bank,
//     |              demux bank
//     |     exposes: fu_in_data/valid/ready, fu_out_data/valid/ready,
//     |              fu_cfg_bits, pe_enable, pe_opcode
//     |
//     +-- per FU: fabric_spatial_pe_fu_slot (pre-written)
//     |     gates ungated mux-bank outputs by opcode match
//     |     exposes: gated fu_in -> FU body, FU body out -> gated out
//     |
//     +-- per FU: fu_<name> body (generated by SVGenFU)
//
// The wrapper wires individual pe_inN / pe_outN ports from the
// top-level to the container's packed-array ports, and routes
// the active FU's gated I/O to/from the container.

std::string generateSpatialPE(fcc::fabric::SpatialPEOp peOp,
                               llvm::raw_ostream &os,
                               SVModuleRegistry &registry,
                               llvm::StringRef fpIpProfile) {
  std::string peName = SVEmitter::sanitizeName(
      peOp.getSymName().value_or("spatial_pe"));
  std::string moduleName = "pe_" + peName;

  auto fnType = peOp.getFunctionType();
  unsigned numPEInputs = fnType.getNumInputs();
  unsigned numPEOutputs = fnType.getNumResults();

  auto fus = collectFUs(peOp.getBody().front());
  unsigned numFU = fus.size();

  // Compute max FU port counts.
  unsigned maxFUIn = 0, maxFUOut = 0, maxFUCfg = 0;
  for (const auto &fu : fus) {
    maxFUIn = std::max(maxFUIn, fu.numInputs);
    maxFUOut = std::max(maxFUOut, fu.numOutputs);
    maxFUCfg = std::max(maxFUCfg, fu.configBits);
  }

  // Determine data width from PE port types.
  unsigned dataWidth = 32;
  if (numPEInputs > 0)
    dataWidth = SVEmitter::getDataWidth(fnType.getInput(0));
  else if (numPEOutputs > 0)
    dataWidth = SVEmitter::getDataWidth(fnType.getResult(0));

  unsigned opcodeBits = numFU > 1 ? llvm::Log2_32_Ceil(numFU) : 0;
  unsigned opcodeRegW = opcodeBits > 0 ? opcodeBits : 1;

  SVEmitter emitter(os);
  emitter.emitFileHeader(moduleName);

  // Require pre-written sub-modules.
  registry.requireModule("fabric/spatial_pe", "fabric_spatial_pe.sv");
  registry.requireModule("fabric/spatial_pe", "fabric_spatial_pe_mux.sv");
  registry.requireModule("fabric/spatial_pe", "fabric_spatial_pe_demux.sv");
  registry.requireModule("fabric/spatial_pe", "fabric_spatial_pe_fu_slot.sv");

  // Module parameters.
  std::vector<std::string> params;
  params.push_back("parameter DATA_WIDTH = " + u2s(dataWidth));

  // Module ports (individual per-port signals as used by the top level).
  std::vector<SVPort> ports;
  ports.push_back({SVPortDir::Input, "logic", "clk"});
  ports.push_back({SVPortDir::Input, "logic", "rst_n"});

  for (unsigned i = 0; i < numPEInputs; ++i) {
    unsigned w = SVEmitter::getDataWidth(fnType.getInput(i));
    ports.push_back({SVPortDir::Input, "logic" + SVEmitter::bitRange(w),
                     "pe_in" + u2s(i)});
    ports.push_back(
        {SVPortDir::Input, "logic", "pe_in_valid" + u2s(i)});
    ports.push_back(
        {SVPortDir::Output, "logic", "pe_in_ready" + u2s(i)});
  }
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    unsigned w = SVEmitter::getDataWidth(fnType.getResult(i));
    ports.push_back({SVPortDir::Output, "logic" + SVEmitter::bitRange(w),
                     "pe_out" + u2s(i)});
    ports.push_back(
        {SVPortDir::Output, "logic", "pe_out_valid" + u2s(i)});
    ports.push_back(
        {SVPortDir::Input, "logic", "pe_out_ready" + u2s(i)});
  }
  ports.push_back({SVPortDir::Input, "logic", "cfg_valid"});
  ports.push_back({SVPortDir::Input, "logic [31:0]", "cfg_wdata"});
  ports.push_back({SVPortDir::Output, "logic", "cfg_ready"});

  emitter.emitModuleHeader(moduleName, params, ports);

  // ---------------------------------------------------------------
  // Packed-array wires for the container interface
  // ---------------------------------------------------------------
  emitter.emitComment("Packed-array wires for container interface");

  // PE input/output aggregation.
  unsigned inPackW = numPEInputs > 0 ? numPEInputs : 1;
  unsigned outPackW = numPEOutputs > 0 ? numPEOutputs : 1;
  emitter.emitWire("logic [" + u2s(inPackW - 1) + ":0]", "agg_in_valid");
  emitter.emitWire("logic [" + u2s(inPackW - 1) + ":0]", "agg_in_ready");
  emitter.emitWire("logic [" + u2s(outPackW - 1) + ":0]", "agg_out_valid");
  emitter.emitWire("logic [" + u2s(outPackW - 1) + ":0]", "agg_out_ready");

  for (unsigned i = 0; i < numPEInputs; ++i) {
    emitter.emitAssign("agg_in_valid[" + u2s(i) + "]",
                       "pe_in_valid" + u2s(i));
    emitter.emitAssign("pe_in_ready" + u2s(i),
                       "agg_in_ready[" + u2s(i) + "]");
  }
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    emitter.emitAssign("pe_out_valid" + u2s(i),
                       "agg_out_valid[" + u2s(i) + "]");
    emitter.emitAssign("agg_out_ready[" + u2s(i) + "]",
                       "pe_out_ready" + u2s(i));
  }
  emitter.emitBlankLine();

  // Container PE-data unpacked array wires.
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_in_data [" + u2s(numPEInputs) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_out_data [" + u2s(numPEOutputs) + "]");

  // Container FU-body-facing wires (MAX_FU_IN / MAX_FU_OUT wide).
  unsigned fuInPackW = maxFUIn > 0 ? maxFUIn : 1;
  unsigned fuOutPackW = maxFUOut > 0 ? maxFUOut : 1;
  unsigned fuCfgW = maxFUCfg > 0 ? maxFUCfg : 1;

  emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                   "ctr_fu_in_valid");
  emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                   "ctr_fu_in_ready");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_fu_in_data [" + u2s(maxFUIn) + "]");
  emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                   "ctr_fu_out_valid");
  emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                   "ctr_fu_out_ready");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_fu_out_data [" + u2s(maxFUOut) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(fuCfgW), "ctr_fu_cfg_bits");
  emitter.emitWire("logic", "ctr_pe_enable");
  emitter.emitWire("logic" + SVEmitter::bitRange(opcodeRegW),
                   "ctr_pe_opcode");
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Instantiate fabric_spatial_pe container
  // ---------------------------------------------------------------
  emitter.emitComment("Instantiate fabric_spatial_pe container");
  {
    std::vector<std::string> ctrParams;
    ctrParams.push_back(".NUM_IN(" + u2s(numPEInputs) + ")");
    ctrParams.push_back(".NUM_OUT(" + u2s(numPEOutputs) + ")");
    ctrParams.push_back(".DATA_WIDTH(DATA_WIDTH)");
    ctrParams.push_back(".NUM_FU(" + u2s(numFU) + ")");
    ctrParams.push_back(".MAX_FU_IN(" + u2s(maxFUIn) + ")");
    ctrParams.push_back(".MAX_FU_OUT(" + u2s(maxFUOut) + ")");
    ctrParams.push_back(".MAX_FU_CFG_BITS(" + u2s(maxFUCfg) + ")");

    std::vector<SVConnection> ctrConns;
    ctrConns.push_back({"clk", "clk"});
    ctrConns.push_back({"rst_n", "rst_n"});
    ctrConns.push_back({"in_valid", "agg_in_valid"});
    ctrConns.push_back({"in_ready", "agg_in_ready"});
    ctrConns.push_back({"in_data", "ctr_in_data"});
    ctrConns.push_back({"out_valid", "agg_out_valid"});
    ctrConns.push_back({"out_ready", "agg_out_ready"});
    ctrConns.push_back({"out_data", "ctr_out_data"});
    ctrConns.push_back({"cfg_valid", "cfg_valid"});
    ctrConns.push_back({"cfg_wdata", "cfg_wdata"});
    ctrConns.push_back({"cfg_ready", "cfg_ready"});
    ctrConns.push_back({"fu_in_valid", "ctr_fu_in_valid"});
    ctrConns.push_back({"fu_in_ready", "ctr_fu_in_ready"});
    ctrConns.push_back({"fu_in_data", "ctr_fu_in_data"});
    ctrConns.push_back({"fu_out_valid", "ctr_fu_out_valid"});
    ctrConns.push_back({"fu_out_ready", "ctr_fu_out_ready"});
    ctrConns.push_back({"fu_out_data", "ctr_fu_out_data"});
    ctrConns.push_back({"fu_cfg_bits", "ctr_fu_cfg_bits"});
    ctrConns.push_back({"pe_enable", "ctr_pe_enable"});
    ctrConns.push_back({"pe_opcode", "ctr_pe_opcode"});

    emitter.emitInstance("fabric_spatial_pe", "u_container",
                         ctrParams, ctrConns);
  }
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Wire individual PE port signals to container unpacked arrays
  // ---------------------------------------------------------------
  emitter.emitComment(
      "Wire individual PE port signals to container unpacked arrays");
  emitter.emitRaw(
      "always_comb begin : wire_pe_in_data\n");
  emitter.indent();
  emitter.emitRaw("integer iter_var0;\n");
  for (unsigned i = 0; i < numPEInputs; ++i) {
    emitter.emitRaw("ctr_in_data[" + u2s(i) + "] = pe_in" + u2s(i) + ";\n");
  }
  emitter.dedent();
  emitter.emitRaw("end // wire_pe_in_data\n");
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    emitter.emitAssign("pe_out" + u2s(i), "ctr_out_data[" + u2s(i) + "]");
  }
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Per-FU: fu_slot gating wrapper + FU body instantiation
  //
  // The container drives ungated mux-bank outputs on ctr_fu_in_*.
  // Each fu_slot gates these by pe_enable && opcode match, producing
  // gated signals for its FU body. The FU body output goes back
  // through the fu_slot's output gate, and only the active FU's
  // gated output feeds the container's demux bank via ctr_fu_out_*.
  // ---------------------------------------------------------------
  emitter.emitComment("Per-FU: fu_slot gating + FU body instantiation");
  emitter.emitBlankLine();

  for (unsigned fuIdx = 0; fuIdx < numFU; ++fuIdx) {
    const auto &fu = fus[fuIdx];
    std::string fp = "fu" + u2s(fuIdx);

    emitter.emitComment("FU " + u2s(fuIdx) + ": " + fu.svModuleName +
                        " (inputs=" + u2s(fu.numInputs) +
                        ", outputs=" + u2s(fu.numOutputs) +
                        ", cfg=" + u2s(fu.configBits) + ")");

    // --- Gated FU input signals (fu_slot -> FU body) ---
    emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                     fp + "_gated_in_valid");
    emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                     fp + "_gated_in_ready");
    emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                     fp + "_gated_in_data [" + u2s(maxFUIn) + "]");

    // --- FU body output signals ---
    emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                     fp + "_body_out_valid");
    emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                     fp + "_body_out_ready");
    emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                     fp + "_body_out_data [" + u2s(maxFUOut) + "]");

    // --- Gated FU output signals (fu_slot -> container demux) ---
    emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                     fp + "_gated_out_valid");
    emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                     fp + "_gated_out_ready");
    emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                     fp + "_gated_out_data [" + u2s(maxFUOut) + "]");

    // --- Ungated in ready from fu_slot (back to container mux) ---
    emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                     fp + "_ungated_in_ready");

    // --- FU config output from slot ---
    unsigned fuCfgBitsForSlot = fu.configBits > 0 ? fu.configBits : 1;
    emitter.emitWire("logic" + SVEmitter::bitRange(fuCfgBitsForSlot),
                     fp + "_cfg_out");
    emitter.emitBlankLine();

    // Instantiate fabric_spatial_pe_fu_slot.
    {
      std::vector<std::string> slotParams;
      slotParams.push_back(".FU_INDEX(" + u2s(fuIdx) + ")");
      slotParams.push_back(".DATA_WIDTH(DATA_WIDTH)");
      slotParams.push_back(".NUM_FU_IN(" + u2s(maxFUIn) + ")");
      slotParams.push_back(".NUM_FU_OUT(" + u2s(maxFUOut) + ")");
      slotParams.push_back(".FU_CFG_BITS(" + u2s(fu.configBits) + ")");
      slotParams.push_back(".OPCODE_WIDTH(" + u2s(opcodeBits) + ")");

      std::vector<SVConnection> slotConns;
      slotConns.push_back({"pe_enable", "ctr_pe_enable"});
      slotConns.push_back({"pe_opcode", "ctr_pe_opcode"});
      slotConns.push_back({"ungated_in_valid", "ctr_fu_in_valid"});
      slotConns.push_back({"ungated_in_ready", fp + "_ungated_in_ready"});
      slotConns.push_back({"ungated_in_data", "ctr_fu_in_data"});
      slotConns.push_back({"fu_in_valid", fp + "_gated_in_valid"});
      slotConns.push_back({"fu_in_ready", fp + "_gated_in_ready"});
      slotConns.push_back({"fu_in_data", fp + "_gated_in_data"});
      slotConns.push_back({"fu_out_valid", fp + "_body_out_valid"});
      slotConns.push_back({"fu_out_ready", fp + "_body_out_ready"});
      slotConns.push_back({"fu_out_data", fp + "_body_out_data"});
      slotConns.push_back({"gated_out_valid", fp + "_gated_out_valid"});
      slotConns.push_back({"gated_out_ready", fp + "_gated_out_ready"});
      slotConns.push_back({"gated_out_data", fp + "_gated_out_data"});
      if (fu.configBits > 0) {
        slotConns.push_back(
            {"fu_cfg_bits",
             "ctr_fu_cfg_bits[" + u2s(fu.configBits - 1) + ":0]"});
      } else {
        slotConns.push_back({"fu_cfg_bits", "1'b0"});
      }
      slotConns.push_back({"fu_cfg_out", fp + "_cfg_out"});

      emitter.emitInstance("fabric_spatial_pe_fu_slot",
                           fp + "_slot", slotParams, slotConns);
    }
    emitter.emitBlankLine();

    // Instantiate FU body module.
    {
      std::vector<std::string> fuParams;
      fuParams.push_back(".DATA_WIDTH(DATA_WIDTH)");

      std::vector<SVConnection> fuConns;
      fuConns.push_back({"clk", "clk"});
      fuConns.push_back({"rst_n", "rst_n"});

      for (unsigned i = 0; i < fu.numInputs; ++i) {
        std::string idx = u2s(i);
        fuConns.push_back(
            {"in_data_" + idx, fp + "_gated_in_data[" + idx + "]"});
        fuConns.push_back(
            {"in_valid_" + idx,
             fp + "_gated_in_valid[" + idx + "]"});
        fuConns.push_back(
            {"in_ready_" + idx,
             fp + "_gated_in_ready[" + idx + "]"});
      }
      for (unsigned i = 0; i < fu.numOutputs; ++i) {
        std::string idx = u2s(i);
        fuConns.push_back(
            {"out_data_" + idx, fp + "_body_out_data[" + idx + "]"});
        fuConns.push_back(
            {"out_valid_" + idx,
             fp + "_body_out_valid[" + idx + "]"});
        fuConns.push_back(
            {"out_ready_" + idx,
             fp + "_body_out_ready[" + idx + "]"});
      }
      if (fu.configBits > 0) {
        fuConns.push_back({"fu_cfg", fp + "_cfg_out"});
      }

      emitter.emitInstance(fu.svModuleName, fp + "_body",
                           fuParams, fuConns);
    }
    emitter.emitBlankLine();
  }

  // ---------------------------------------------------------------
  // Combine per-FU slot outputs to feed container's fu_out interface.
  // Only the active FU (opcode match) drives the container's fu_out.
  // Inactive FU slots already produce zero on their gated outputs.
  // ---------------------------------------------------------------
  emitter.emitComment(
      "Combine per-FU gated outputs to container fu_out interface");
  emitter.emitRaw("always_comb begin : combine_fu_out\n");
  emitter.indent();
  emitter.emitRaw("integer iter_var0;\n");
  emitter.emitRaw("ctr_fu_out_valid = '0;\n");
  for (unsigned i = 0; i < maxFUOut; ++i) {
    emitter.emitRaw("ctr_fu_out_data[" + u2s(i) + "] = '0;\n");
  }

  for (unsigned fuIdx = 0; fuIdx < numFU; ++fuIdx) {
    std::string fp = "fu" + u2s(fuIdx);
    std::string condStr = "ctr_pe_enable && (" + u2s(opcodeRegW) + "'d" +
                          u2s(fuIdx) + " == ctr_pe_opcode)";
    emitter.emitRaw("if (" + condStr + ") begin : " + fp + "_sel\n");
    emitter.indent();
    emitter.emitRaw("ctr_fu_out_valid = " + fp + "_gated_out_valid;\n");
    for (unsigned i = 0; i < maxFUOut; ++i) {
      emitter.emitRaw("ctr_fu_out_data[" + u2s(i) + "] = " + fp +
                       "_gated_out_data[" + u2s(i) + "];\n");
    }
    emitter.dedent();
    emitter.emitRaw("end // " + fp + "_sel\n");
  }
  emitter.dedent();
  emitter.emitRaw("end // combine_fu_out\n");
  emitter.emitBlankLine();

  // Combine per-FU ungated_in_ready -> container fu_in_ready.
  emitter.emitComment(
      "Combine per-FU ungated_in_ready to container fu_in_ready");
  emitter.emitRaw("always_comb begin : combine_fu_in_ready\n");
  emitter.indent();
  emitter.emitRaw("ctr_fu_in_ready = '0;\n");
  for (unsigned fuIdx = 0; fuIdx < numFU; ++fuIdx) {
    std::string fp = "fu" + u2s(fuIdx);
    std::string condStr = "ctr_pe_enable && (" + u2s(opcodeRegW) + "'d" +
                          u2s(fuIdx) + " == ctr_pe_opcode)";
    emitter.emitRaw("if (" + condStr + ") begin : " + fp + "_rdy\n");
    emitter.indent();
    emitter.emitRaw("ctr_fu_in_ready = " + fp + "_ungated_in_ready;\n");
    emitter.dedent();
    emitter.emitRaw("end // " + fp + "_rdy\n");
  }
  emitter.dedent();
  emitter.emitRaw("end // combine_fu_in_ready\n");
  emitter.emitBlankLine();

  // Feed container fu_out_ready to each fu_slot's gated_out_ready.
  emitter.emitComment(
      "Feed container fu_out_ready back to each fu_slot");
  for (unsigned fuIdx = 0; fuIdx < numFU; ++fuIdx) {
    std::string fp = "fu" + u2s(fuIdx);
    emitter.emitAssign(fp + "_gated_out_ready", "ctr_fu_out_ready");
  }
  emitter.emitBlankLine();

  emitter.emitModuleFooter(moduleName);
  return moduleName;
}

// =================================================================
// generateTemporalPE
// =================================================================
//
// Generated wrapper module architecture:
//
//   pe_<name> (wrapper, generated by this C++)
//     +-- fabric_temporal_pe (container, pre-written)
//     |     handles: imem (config + tag-match), operand buffering,
//     |              regfile, scheduler, fu_slot pipelines,
//     |              output_arb
//     |     exposes: per-FU fu_fire[], fu_in_data[][], fu_in_valid[][],
//     |              fu_out_valid[][], fu_out_data[][], fu_cfg_bits
//     |
//     +-- per FU: fu_<name> body (generated by SVGenFU)
//
// The container handles all the temporal scheduling internally.
// This wrapper only needs to:
//   1. Aggregate individual PE port signals to packed arrays
//   2. Split tagged ports into data+tag components
//   3. Instantiate FU body modules and connect them to the
//      container's per-FU data/fire interface

std::string generateTemporalPE(fcc::fabric::TemporalPEOp peOp,
                                llvm::raw_ostream &os,
                                SVModuleRegistry &registry,
                                llvm::StringRef fpIpProfile) {
  std::string peName = SVEmitter::sanitizeName(
      peOp.getSymName().value_or("temporal_pe"));
  std::string moduleName = "pe_" + peName;

  auto fnType = peOp.getFunctionType();
  unsigned numPEInputs = fnType.getNumInputs();
  unsigned numPEOutputs = fnType.getNumResults();
  unsigned numInstruction = static_cast<unsigned>(peOp.getNumInstruction());
  unsigned numRegister = static_cast<unsigned>(peOp.getNumRegister());
  unsigned regFifoDepth = static_cast<unsigned>(peOp.getRegFifoDepth());
  bool enableShareOperandBuf = peOp.getEnableShareOperandBuffer();
  unsigned operandBufSize = 8;
  if (auto obs = peOp.getOperandBufferSize())
    operandBufSize = static_cast<unsigned>(*obs);

  auto fus = collectFUs(peOp.getBody().front());
  unsigned numFU = fus.size();

  // Compute max FU port counts and total persistent FU config bits.
  unsigned maxFUIn = 0, maxFUOut = 0;
  unsigned totalFUCfgBits = 0;
  for (const auto &fu : fus) {
    maxFUIn = std::max(maxFUIn, fu.numInputs);
    maxFUOut = std::max(maxFUOut, fu.numOutputs);
    totalFUCfgBits += fu.configBits;
  }

  unsigned dataWidth = 32;
  unsigned tagWidth = 0;
  if (numPEInputs > 0) {
    dataWidth = SVEmitter::getDataWidth(fnType.getInput(0));
    tagWidth = SVEmitter::getTagWidth(fnType.getInput(0));
  }
  if (tagWidth == 0)
    tagWidth = 1;

  unsigned totalPortWidth = dataWidth + tagWidth;

  // Per-FU latency/interval for container parameter arrays.
  struct FUTimingInfo {
    int64_t latency = 0;
    unsigned intrinsic = 0;
    int64_t interval = 1;
  };
  std::vector<FUTimingInfo> fuTimings(numFU);
  for (unsigned i = 0; i < numFU; ++i) {
    if (auto lat = fus[i].fuOp.getLatency())
      fuTimings[i].latency = *lat;
    if (auto intv = fus[i].fuOp.getInterval())
      fuTimings[i].interval = *intv;
    fuTimings[i].intrinsic = computeFUIntrinsicLatency(fus[i].fuOp);

    // Validate timing constraints; abort generation on violation.
    if (!validateFUTimingConstraints(fus[i].fuOp))
      return "";
  }

  SVEmitter emitter(os);
  emitter.emitFileHeader(moduleName);

  // Require pre-written sub-modules.
  registry.requireModule("fabric/temporal_pe", "fabric_temporal_pe.sv");
  registry.requireModule("fabric/temporal_pe", "fabric_temporal_pe_imem.sv");
  registry.requireModule("fabric/temporal_pe",
                         "fabric_temporal_pe_operand.sv");
  registry.requireModule("fabric/temporal_pe",
                         "fabric_temporal_pe_regfile.sv");
  registry.requireModule("fabric/temporal_pe",
                         "fabric_temporal_pe_scheduler.sv");
  registry.requireModule("fabric/temporal_pe",
                         "fabric_temporal_pe_output_arb.sv");
  registry.requireModule("fabric/temporal_pe",
                         "fabric_temporal_pe_fu_slot.sv");
  registry.requireModule("common", "fabric_fifo_mem.sv");
  registry.requireModule("common", "fabric_rr_arbiter.sv");

  // Module parameters.
  std::vector<std::string> params;
  params.push_back("parameter DATA_WIDTH = " + u2s(dataWidth));
  params.push_back("parameter TAG_WIDTH = " + u2s(tagWidth));

  // Module ports.
  std::vector<SVPort> ports;
  ports.push_back({SVPortDir::Input, "logic", "clk"});
  ports.push_back({SVPortDir::Input, "logic", "rst_n"});

  for (unsigned i = 0; i < numPEInputs; ++i) {
    ports.push_back(
        {SVPortDir::Input,
         "logic" + SVEmitter::bitRange(totalPortWidth),
         "pe_in" + u2s(i)});
    ports.push_back(
        {SVPortDir::Input, "logic", "pe_in_valid" + u2s(i)});
    ports.push_back(
        {SVPortDir::Output, "logic", "pe_in_ready" + u2s(i)});
  }
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    ports.push_back(
        {SVPortDir::Output,
         "logic" + SVEmitter::bitRange(totalPortWidth),
         "pe_out" + u2s(i)});
    ports.push_back(
        {SVPortDir::Output, "logic", "pe_out_valid" + u2s(i)});
    ports.push_back(
        {SVPortDir::Input, "logic", "pe_out_ready" + u2s(i)});
  }
  ports.push_back({SVPortDir::Input, "logic", "cfg_valid"});
  ports.push_back({SVPortDir::Input, "logic [31:0]", "cfg_wdata"});
  ports.push_back({SVPortDir::Output, "logic", "cfg_ready"});

  emitter.emitModuleHeader(moduleName, params, ports);

  // ---------------------------------------------------------------
  // Packed-array wires for the container interface
  // ---------------------------------------------------------------
  emitter.emitComment("Packed-array wires for container interface");

  unsigned inPackW = numPEInputs > 0 ? numPEInputs : 1;
  unsigned outPackW = numPEOutputs > 0 ? numPEOutputs : 1;
  unsigned fuInPackW = maxFUIn > 0 ? maxFUIn : 1;
  unsigned fuOutPackW = maxFUOut > 0 ? maxFUOut : 1;
  unsigned fuCfgW = totalFUCfgBits > 0 ? totalFUCfgBits : 1;

  emitter.emitWire("logic [" + u2s(inPackW - 1) + ":0]", "agg_in_valid");
  emitter.emitWire("logic [" + u2s(inPackW - 1) + ":0]", "agg_in_ready");
  emitter.emitWire("logic [" + u2s(outPackW - 1) + ":0]", "agg_out_valid");
  emitter.emitWire("logic [" + u2s(outPackW - 1) + ":0]", "agg_out_ready");
  emitter.emitWire("logic" + SVEmitter::bitRange(fuCfgW), "ctr_fu_cfg_bits");

  // Container PE-data unpacked arrays.
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_pe_in_data [" + u2s(numPEInputs) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(tagWidth),
                   "ctr_pe_in_tag [" + u2s(numPEInputs) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_pe_out_data [" + u2s(numPEOutputs) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(tagWidth),
                   "ctr_pe_out_tag [" + u2s(numPEOutputs) + "]");

  // Container FU-body unpacked arrays.
  // fu_fire[NUM_FU], fu_in_data[NUM_FU][MAX_FU_IN],
  // fu_in_valid[NUM_FU], fu_out_valid[NUM_FU], fu_out_data[NUM_FU][MAX_FU_OUT]
  emitter.emitWire("logic", "ctr_fu_fire [" + u2s(numFU) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_fu_in_data [" + u2s(numFU) + "][" + u2s(maxFUIn) + "]");
  emitter.emitWire("logic [" + u2s(fuInPackW - 1) + ":0]",
                   "ctr_fu_in_valid [" + u2s(numFU) + "]");
  emitter.emitWire("logic [" + u2s(fuOutPackW - 1) + ":0]",
                   "ctr_fu_out_valid [" + u2s(numFU) + "]");
  emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                   "ctr_fu_out_data [" + u2s(numFU) + "][" + u2s(maxFUOut) + "]");
  emitter.emitBlankLine();

  for (unsigned i = 0; i < numPEInputs; ++i) {
    emitter.emitAssign("agg_in_valid[" + u2s(i) + "]",
                       "pe_in_valid" + u2s(i));
    emitter.emitAssign("pe_in_ready" + u2s(i),
                       "agg_in_ready[" + u2s(i) + "]");
  }
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    emitter.emitAssign("pe_out_valid" + u2s(i),
                       "agg_out_valid[" + u2s(i) + "]");
    emitter.emitAssign("agg_out_ready[" + u2s(i) + "]",
                       "pe_out_ready" + u2s(i));
  }
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Split/combine tagged PE port signals to data+tag arrays
  // ---------------------------------------------------------------
  emitter.emitComment(
      "Split/combine tagged PE port signals to data+tag arrays");
  emitter.emitRaw("always_comb begin : wire_pe_ports\n");
  emitter.indent();
  emitter.emitRaw("integer iter_var0;\n");
  for (unsigned i = 0; i < numPEInputs; ++i) {
    emitter.emitRaw("ctr_pe_in_data[" + u2s(i) + "] = pe_in" + u2s(i) +
                     "[DATA_WIDTH-1:0];\n");
    emitter.emitRaw("ctr_pe_in_tag[" + u2s(i) + "] = pe_in" + u2s(i) +
                     "[DATA_WIDTH+TAG_WIDTH-1:DATA_WIDTH];\n");
  }
  for (unsigned i = 0; i < numPEOutputs; ++i) {
    emitter.emitRaw("pe_out" + u2s(i) + " = {ctr_pe_out_tag[" + u2s(i) +
                     "], ctr_pe_out_data[" + u2s(i) + "]};\n");
  }
  emitter.dedent();
  emitter.emitRaw("end // wire_pe_ports\n");
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Instantiate fabric_temporal_pe container
  // ---------------------------------------------------------------
  emitter.emitComment("Instantiate fabric_temporal_pe container");
  {
    std::vector<std::string> ctrParams;
    ctrParams.push_back(".NUM_IN(" + u2s(numPEInputs) + ")");
    ctrParams.push_back(".NUM_OUT(" + u2s(numPEOutputs) + ")");
    ctrParams.push_back(".DATA_WIDTH(DATA_WIDTH)");
    ctrParams.push_back(".TAG_WIDTH(TAG_WIDTH)");
    ctrParams.push_back(".NUM_FU(" + u2s(numFU) + ")");
    ctrParams.push_back(".NUM_INSTR(" + u2s(numInstruction) + ")");
    ctrParams.push_back(".NUM_REG(" + u2s(numRegister) + ")");
    ctrParams.push_back(".REG_FIFO_DEPTH(" + u2s(regFifoDepth) + ")");
    ctrParams.push_back(".MAX_FU_IN(" + u2s(maxFUIn) + ")");
    ctrParams.push_back(".MAX_FU_OUT(" + u2s(maxFUOut) + ")");
    ctrParams.push_back(".ENABLE_SHARE_OPERAND_BUF(" +
                        std::string(enableShareOperandBuf ? "1'b1" : "1'b0") +
                        ")");
    ctrParams.push_back(".OPERAND_BUF_SIZE(" + u2s(operandBufSize) + ")");
    ctrParams.push_back(".TOTAL_FU_CFG_BITS(" + u2s(totalFUCfgBits) + ")");

    // Per-FU packed parameter arrays.
    auto buildUnsignedArray = [&](const std::string &paramName,
                                  const std::vector<unsigned> &vals) {
      std::string val = "'{";
      for (unsigned i = 0; i < vals.size(); ++i) {
        if (i > 0) val += ", ";
        val += u2s(vals[i]);
      }
      val += "}";
      ctrParams.push_back("." + paramName + "(" + val + ")");
    };
    auto buildSignedArray = [&](const std::string &paramName,
                                const std::vector<int64_t> &vals) {
      std::string val = "'{";
      for (unsigned i = 0; i < vals.size(); ++i) {
        if (i > 0) val += ", ";
        val += s2s(vals[i]);
      }
      val += "}";
      ctrParams.push_back("." + paramName + "(" + val + ")");
    };

    std::vector<unsigned> fuNumInputs, fuNumOutputs, fuIntrinsic;
    std::vector<int64_t> fuLatency, fuInterval;
    for (unsigned i = 0; i < numFU; ++i) {
      fuNumInputs.push_back(fus[i].numInputs);
      fuNumOutputs.push_back(fus[i].numOutputs);
      fuLatency.push_back(fuTimings[i].latency);
      fuIntrinsic.push_back(fuTimings[i].intrinsic);
      fuInterval.push_back(fuTimings[i].interval);
    }
    buildUnsignedArray("FU_NUM_INPUTS", fuNumInputs);
    buildUnsignedArray("FU_NUM_OUTPUTS", fuNumOutputs);
    buildSignedArray("FU_LATENCY", fuLatency);
    buildUnsignedArray("FU_INTRINSIC", fuIntrinsic);
    buildSignedArray("FU_INTERVAL", fuInterval);

    std::vector<SVConnection> ctrConns;
    ctrConns.push_back({"clk", "clk"});
    ctrConns.push_back({"rst_n", "rst_n"});
    ctrConns.push_back({"cfg_valid", "cfg_valid"});
    ctrConns.push_back({"cfg_wdata", "cfg_wdata"});
    ctrConns.push_back({"pe_in_valid", "agg_in_valid"});
    ctrConns.push_back({"pe_in_ready", "agg_in_ready"});
    ctrConns.push_back({"pe_in_data", "ctr_pe_in_data"});
    ctrConns.push_back({"pe_in_tag", "ctr_pe_in_tag"});
    ctrConns.push_back({"pe_out_valid", "agg_out_valid"});
    ctrConns.push_back({"pe_out_ready", "agg_out_ready"});
    ctrConns.push_back({"pe_out_data", "ctr_pe_out_data"});
    ctrConns.push_back({"pe_out_tag", "ctr_pe_out_tag"});
    ctrConns.push_back({"fu_fire", "ctr_fu_fire"});
    ctrConns.push_back({"fu_in_data", "ctr_fu_in_data"});
    ctrConns.push_back({"fu_in_valid", "ctr_fu_in_valid"});
    ctrConns.push_back({"fu_out_valid", "ctr_fu_out_valid"});
    ctrConns.push_back({"fu_out_data", "ctr_fu_out_data"});
    ctrConns.push_back({"fu_cfg_bits", "ctr_fu_cfg_bits"});

    emitter.emitInstance("fabric_temporal_pe", "u_container",
                         ctrParams, ctrConns);
  }
  emitter.emitBlankLine();

  // ---------------------------------------------------------------
  // Wire container FU arrays to per-FU body signals and
  // instantiate FU body modules
  // ---------------------------------------------------------------
  emitter.emitComment("FU body instantiations");

  // Track config bit offset within the persistent FU config region.
  unsigned fuCfgOffset = 0;

  for (unsigned fuIdx = 0; fuIdx < numFU; ++fuIdx) {
    const auto &fu = fus[fuIdx];
    std::string fp = "fu" + u2s(fuIdx);

    emitter.emitComment("FU " + u2s(fuIdx) + ": " + fu.svModuleName +
                        " (inputs=" + u2s(fu.numInputs) +
                        ", outputs=" + u2s(fu.numOutputs) +
                        ", cfg=" + u2s(fu.configBits) + ")");

    // FU body I/O wires.
    for (unsigned i = 0; i < fu.numInputs; ++i) {
      emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                       fp + "_body_in" + u2s(i));
    }
    for (unsigned i = 0; i < fu.numOutputs; ++i) {
      emitter.emitWire("logic" + SVEmitter::bitRange(dataWidth),
                       fp + "_body_out" + u2s(i));
    }
    emitter.emitWire("logic [" +
                         u2s(fu.numInputs > 0 ? fu.numInputs - 1 : 0) +
                         ":0]",
                     fp + "_body_in_valid");
    emitter.emitWire("logic [" +
                         u2s(fu.numInputs > 0 ? fu.numInputs - 1 : 0) +
                         ":0]",
                     fp + "_body_in_ready");
    emitter.emitWire("logic [" +
                         u2s(fu.numOutputs > 0 ? fu.numOutputs - 1 : 0) +
                         ":0]",
                     fp + "_body_out_valid");
    emitter.emitWire("logic [" +
                         u2s(fu.numOutputs > 0 ? fu.numOutputs - 1 : 0) +
                         ":0]",
                     fp + "_body_out_ready");
    emitter.emitBlankLine();

    // Wire container inputs to FU body.
    emitter.emitRaw("always_comb begin : " + fp + "_wire_in\n");
    emitter.indent();
    emitter.emitRaw("integer iter_var0;\n");
    for (unsigned i = 0; i < fu.numInputs; ++i) {
      emitter.emitRaw(fp + "_body_in" + u2s(i) + " = ctr_fu_in_data[" +
                       u2s(fuIdx) + "][" + u2s(i) + "];\n");
    }
    emitter.emitRaw(fp + "_body_in_valid = ctr_fu_in_valid[" + u2s(fuIdx) +
                     "][" + u2s(fu.numInputs > 0 ? fu.numInputs - 1 : 0) +
                     ":0];\n");
    emitter.dedent();
    emitter.emitRaw("end // " + fp + "_wire_in\n");

    // Wire FU body outputs to container.
    emitter.emitRaw("always_comb begin : " + fp + "_wire_out\n");
    emitter.indent();
    emitter.emitRaw("integer iter_var0;\n");
    // Default: zero-fill the full MAX_FU_OUT-wide packed vector.
    emitter.emitRaw("ctr_fu_out_valid[" + u2s(fuIdx) + "] = '0;\n");
    for (unsigned i = 0; i < maxFUOut; ++i) {
      if (i < fu.numOutputs) {
        emitter.emitRaw("ctr_fu_out_data[" + u2s(fuIdx) + "][" + u2s(i) +
                         "] = " + fp + "_body_out" + u2s(i) + ";\n");
        emitter.emitRaw("ctr_fu_out_valid[" + u2s(fuIdx) + "][" + u2s(i) +
                         "] = " + fp + "_body_out_valid[" + u2s(i) + "];\n");
      } else {
        emitter.emitRaw("ctr_fu_out_data[" + u2s(fuIdx) + "][" + u2s(i) +
                         "] = '0;\n");
      }
    }
    // out_ready from container is always driven as 1'b1 for combinational
    // FU bodies; for pipelined bodies the container fu_slot handles it.
    emitter.emitRaw(fp + "_body_out_ready = '1;\n");
    emitter.dedent();
    emitter.emitRaw("end // " + fp + "_wire_out\n");
    emitter.emitBlankLine();

    // Instantiate FU body module.
    {
      std::vector<std::string> fuParams;
      fuParams.push_back(".DATA_WIDTH(DATA_WIDTH)");

      std::vector<SVConnection> fuConns;
      fuConns.push_back({"clk", "clk"});
      fuConns.push_back({"rst_n", "rst_n"});

      for (unsigned i = 0; i < fu.numInputs; ++i) {
        std::string idx = u2s(i);
        fuConns.push_back(
            {"in_data_" + idx, fp + "_body_in" + idx});
        fuConns.push_back(
            {"in_valid_" + idx,
             fp + "_body_in_valid[" + idx + "]"});
        fuConns.push_back(
            {"in_ready_" + idx,
             fp + "_body_in_ready[" + idx + "]"});
      }
      for (unsigned i = 0; i < fu.numOutputs; ++i) {
        std::string idx = u2s(i);
        fuConns.push_back(
            {"out_data_" + idx, fp + "_body_out" + idx});
        fuConns.push_back(
            {"out_valid_" + idx,
             fp + "_body_out_valid[" + idx + "]"});
        fuConns.push_back(
            {"out_ready_" + idx,
             fp + "_body_out_ready[" + idx + "]"});
      }

      if (fu.configBits > 0) {
        std::string cfgSlice = "ctr_fu_cfg_bits[" +
                               u2s(fuCfgOffset + fu.configBits - 1) + ":" +
                               u2s(fuCfgOffset) + "]";
        fuConns.push_back({"fu_cfg", cfgSlice});
      }

      // Memory-side port connections: pass through to PE boundary ports.
      std::string memPfx = fp + "_";
      if (fu.memOpType == "load") {
        fuConns.push_back({"mem_addr", memPfx + "mem_addr"});
        fuConns.push_back({"mem_addr_valid", memPfx + "mem_addr_valid"});
        fuConns.push_back({"mem_addr_ready", memPfx + "mem_addr_ready"});
        fuConns.push_back({"mem_rdata", memPfx + "mem_rdata"});
        fuConns.push_back({"mem_rdata_valid", memPfx + "mem_rdata_valid"});
        fuConns.push_back({"mem_rdata_ready", memPfx + "mem_rdata_ready"});
      } else if (fu.memOpType == "store") {
        fuConns.push_back({"mem_addr", memPfx + "mem_addr"});
        fuConns.push_back({"mem_wdata", memPfx + "mem_wdata"});
        fuConns.push_back({"mem_valid", memPfx + "mem_valid"});
        fuConns.push_back({"mem_ready", memPfx + "mem_ready"});
      }

      emitter.emitInstance(fu.svModuleName, fp + "_body",
                           fuParams, fuConns);
    }
    emitter.emitBlankLine();

    fuCfgOffset += fu.configBits;
  }

  // cfg_ready is driven by the container (always 1'b1 internally),
  // but we expose it here for the top-level connection.
  emitter.emitAssign("cfg_ready", "1'b1");
  emitter.emitBlankLine();

  emitter.emitModuleFooter(moduleName);
  return moduleName;
}

} // namespace svgen
} // namespace fcc
